<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Your First LoRA Fine-Tune – Fine-Tuning Local LLM for Drilling &amp; Completions</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chapter_06.html" rel="next">
<link href="../chapters/chapter_04.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-5a1953863e1f72ef3b996ef827f01ca7.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-911692c0363b1c18dee0691a3385c10d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-f352355e9c4cf757a45f4f8798595620.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-911692c0363b1c18dee0691a3385c10d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapter_01.html">Part I — Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/chapter_05.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Your First LoRA Fine-Tune</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Fine-Tuning Local LLM for Drilling &amp; Completions</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/djimrastephane/llm-ft-drilling-completions-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Fine-Tuning-Local-LLM-for-Drilling---Completions.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 0 — Preparing Your Local LLM Workshop</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_00.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part 0: Preparing Your Local LLM Workshop</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Loading and Running Your First Local LLM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Turning Drilling &amp; Completions Reports into Training Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Baseline Prompting: What the Model Gets Wrong Before Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Tokenization and Embeddings for Domain Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_05.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Your First LoRA Fine-Tune</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Industrialising the System</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">A Data Quality Gate for Training Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Formatting and Chunking a Training Set at Scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fine-Tuning at Scale with Checkpointing and Experiment Tracking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hybrid System: Combining Fine-Tuning with Retrieval</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Traceable Outputs and Hallucination Mitigation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Evaluating a Fine-Tuned Domain Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Detecting Drift Across Model Versions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter_13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Continuous Fine-Tuning: Keeping the Model Current</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a_environment_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A: Environment Setup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a1_jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A1: Using Jupyter Notebook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a2_vscode.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A2: Using VS Code</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a3_pycharm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A3: Using PyCharm Community</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a4_positron.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A4: Using Positron</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_a5_terminal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix A5: Terminal Only</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/appendix_b_glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix B: Drilling, Completions &amp; Fine-Tuning Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">5.1</span> Learning objectives</a></li>
  <li><a href="#operational-problem" id="toc-operational-problem" class="nav-link" data-scroll-target="#operational-problem"><span class="header-section-number">5.2</span> Operational Problem</a></li>
  <li><a href="#example-what-the-model-actually-trains-on" id="toc-example-what-the-model-actually-trains-on" class="nav-link" data-scroll-target="#example-what-the-model-actually-trains-on"><span class="header-section-number">5.3</span> Example: what the model actually trains on</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory"><span class="header-section-number">5.4</span> Theory</a></li>
  <li><a href="#why-lora-instead-of-updating-the-whole-model" id="toc-why-lora-instead-of-updating-the-whole-model" class="nav-link" data-scroll-target="#why-lora-instead-of-updating-the-whole-model"><span class="header-section-number">5.5</span> Why LoRA instead of updating the whole model?</a></li>
  <li><a href="#implementation" id="toc-implementation" class="nav-link" data-scroll-target="#implementation"><span class="header-section-number">5.6</span> Implementation</a>
  <ul class="collapse">
  <li><a href="#step-1-format-a-training-example-and-mask-the-prompt-out-of-the-loss" id="toc-step-1-format-a-training-example-and-mask-the-prompt-out-of-the-loss" class="nav-link" data-scroll-target="#step-1-format-a-training-example-and-mask-the-prompt-out-of-the-loss"><span class="header-section-number">5.6.1</span> Step 1: Format a training example and mask the prompt out of the loss</a></li>
  </ul></li>
  <li><a href="#what-problem-are-we-solving" id="toc-what-problem-are-we-solving" class="nav-link" data-scroll-target="#what-problem-are-we-solving"><span class="header-section-number">5.7</span> What problem are we solving?</a></li>
  <li><a href="#inputs" id="toc-inputs" class="nav-link" data-scroll-target="#inputs"><span class="header-section-number">5.8</span> Inputs</a></li>
  <li><a href="#expected-output" id="toc-expected-output" class="nav-link" data-scroll-target="#expected-output"><span class="header-section-number">5.9</span> Expected Output</a></li>
  <li><a href="#what-just-happened" id="toc-what-just-happened" class="nav-link" data-scroll-target="#what-just-happened"><span class="header-section-number">5.10</span> What just happened?</a></li>
  <li><a href="#production-reality" id="toc-production-reality" class="nav-link" data-scroll-target="#production-reality"><span class="header-section-number">5.11</span> Production Reality</a>
  <ul class="collapse">
  <li><a href="#step-2-wrap-the-base-model-with-a-lora-adapter" id="toc-step-2-wrap-the-base-model-with-a-lora-adapter" class="nav-link" data-scroll-target="#step-2-wrap-the-base-model-with-a-lora-adapter"><span class="header-section-number">5.11.1</span> Step 2: Wrap the base model with a LoRA adapter</a></li>
  </ul></li>
  <li><a href="#what-problem-are-we-solving-1" id="toc-what-problem-are-we-solving-1" class="nav-link" data-scroll-target="#what-problem-are-we-solving-1"><span class="header-section-number">5.12</span> What problem are we solving?</a></li>
  <li><a href="#inputs-1" id="toc-inputs-1" class="nav-link" data-scroll-target="#inputs-1"><span class="header-section-number">5.13</span> Inputs</a></li>
  <li><a href="#expected-output-1" id="toc-expected-output-1" class="nav-link" data-scroll-target="#expected-output-1"><span class="header-section-number">5.14</span> Expected Output</a></li>
  <li><a href="#what-just-happened-1" id="toc-what-just-happened-1" class="nav-link" data-scroll-target="#what-just-happened-1"><span class="header-section-number">5.15</span> What just happened?</a></li>
  <li><a href="#production-reality-1" id="toc-production-reality-1" class="nav-link" data-scroll-target="#production-reality-1"><span class="header-section-number">5.16</span> Production Reality</a>
  <ul class="collapse">
  <li><a href="#step-3-fine-tune-then-measure-recall-and-generalization" id="toc-step-3-fine-tune-then-measure-recall-and-generalization" class="nav-link" data-scroll-target="#step-3-fine-tune-then-measure-recall-and-generalization"><span class="header-section-number">5.16.1</span> Step 3: Fine-tune, then measure recall <em>and</em> generalization</a></li>
  </ul></li>
  <li><a href="#what-problem-are-we-solving-2" id="toc-what-problem-are-we-solving-2" class="nav-link" data-scroll-target="#what-problem-are-we-solving-2"><span class="header-section-number">5.17</span> What problem are we solving?</a></li>
  <li><a href="#inputs-2" id="toc-inputs-2" class="nav-link" data-scroll-target="#inputs-2"><span class="header-section-number">5.18</span> Inputs</a></li>
  <li><a href="#expected-output-2" id="toc-expected-output-2" class="nav-link" data-scroll-target="#expected-output-2"><span class="header-section-number">5.19</span> Expected Output</a></li>
  <li><a href="#what-just-happened-2" id="toc-what-just-happened-2" class="nav-link" data-scroll-target="#what-just-happened-2"><span class="header-section-number">5.20</span> What just happened?</a></li>
  <li><a href="#practical-exercise" id="toc-practical-exercise" class="nav-link" data-scroll-target="#practical-exercise"><span class="header-section-number">5.21</span> Practical exercise</a></li>
  <li><a href="#field-notes" id="toc-field-notes" class="nav-link" data-scroll-target="#field-notes"><span class="header-section-number">5.22</span> Field notes</a></li>
  <li><a href="#challenge-exercise" id="toc-challenge-exercise" class="nav-link" data-scroll-target="#challenge-exercise"><span class="header-section-number">5.23</span> Challenge exercise</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">5.24</span> Key takeaways</a></li>
  <li><a href="#repository-files" id="toc-repository-files" class="nav-link" data-scroll-target="#repository-files"><span class="header-section-number">5.25</span> Repository files</a></li>
  <li><a href="#what-can-you-do-now-that-you-couldnt-do-before" id="toc-what-can-you-do-now-that-you-couldnt-do-before" class="nav-link" data-scroll-target="#what-can-you-do-now-that-you-couldnt-do-before"><span class="header-section-number">5.26</span> What can you do now that you couldn’t do before?</a></li>
  <li><a href="#suggested-next-step" id="toc-suggested-next-step" class="nav-link" data-scroll-target="#suggested-next-step"><span class="header-section-number">5.27</span> Suggested next step</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/djimrastephane/llm-ft-drilling-completions-book/edit/main/chapters/chapter_05.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/djimrastephane/llm-ft-drilling-completions-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapter_01.html">Part I — Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/chapter_05.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Your First LoRA Fine-Tune</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-chapter-05" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Your First LoRA Fine-Tune</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="pipeline-diagram">
<p><img src="../figures/diagrams/pipeline_ch05_light.svg" class="diagram-light img-fluid" width="180"> <img src="../figures/diagrams/pipeline_ch05_dark.svg" class="diagram-dark img-fluid" width="180"></p>
</div>
<div class="chapter-status">
<p>Progress <code>█████░░░░░░░░</code> <strong>5 / 13</strong> &nbsp;·&nbsp; <strong>Estimated time:</strong> 45-60 min &nbsp;·&nbsp; <strong>Difficulty:</strong> 🟠 Intermediate</p>
</div>
<section id="learning-objectives" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">5.1</span> Learning objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li>Explain what a LoRA adapter is: a small set of extra weights trained on top of a frozen base model, not a rewrite of the model itself</li>
<li>Fine-tune the base model on Chapter 2’s 16 training examples with a plain PyTorch training loop — no framework magic hidden from you</li>
<li>Rerun Chapter 3’s training baseline against your fine-tuned model and measure a real, honest improvement</li>
<li>Run, for the first time in this book, a held-out generalization check against Chapter 2’s reserved report — and explain, from a real run, exactly <em>how</em> the fine-tuned model fails on it</li>
</ul>
</section>
<section id="operational-problem" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="operational-problem"><span class="header-section-number">5.2</span> Operational Problem</h2>
<p>Mike, the completions engineer, has watched this book build up evidence for four chapters — the base model doesn’t know this well’s vocabulary, doesn’t know its specific reports, and its embeddings don’t already understand the shorthand. He’s ready for the payoff, but wary of a different failure: <em>“If we fine-tune this on sixteen examples, are we teaching it our operation — or just teaching it to repeat sixteen sentences back at us?”</em></p>
<p>That’s exactly the right question, and this chapter answers it two ways, not one. It fine-tunes the base model on Chapter 2’s 16 training examples, then checks <em>both</em> whether it learned those exact examples (training recall) <em>and</em> whether that learning transfers to a report it never saw during training (generalization, using Chapter 2’s reserved <code>Drilling_037</code>). Chapter 3 already scored the base model <code>0/16</code> and <code>0/2</code> on both. This chapter reruns that exact same harness against the fine-tuned model — same questions, same scoring, same code — so the comparison means something.</p>
</section>
<section id="example-what-the-model-actually-trains-on" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="example-what-the-model-actually-trains-on"><span class="header-section-number">5.3</span> Example: what the model actually trains on</h2>
<p>Fine-tuning doesn’t feed the model <code>instruction</code>/<code>input</code>/<code>output</code> dictionaries directly — it feeds it the same chat-formatted text Chapter 1’s <code>generate_reply</code> builds, except this time with the correct answer appended as the assistant’s turn:</p>
<div class="callout callout-style-default callout-note callout-titled" title="What one training example looks like, chat-formatted">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What one training example looks like, chat-formatted
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>&lt;|im_start|&gt;system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.&lt;|im_end|&gt;
&lt;|im_start|&gt;user
What are the present operations reported on this well?
Well: FORGE 16A [78]-32 | Report #3 | Date: 2020-10-22&lt;|im_end|&gt;
&lt;|im_start|&gt;assistant
RIGGING UP WITH FRONTIER CREWS AND SUPERVISION AND JW JONES TRUCKING&lt;|im_end|&gt;</code></pre>
</div>
</div>
<p>Fine-tuning’s whole job is to adjust the model so that, given the <code>system</code> and <code>user</code> turns above, it becomes more likely to produce that exact <code>assistant</code> turn — and nothing else changes about how the model reads or generates text.</p>
</section>
<section id="theory" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="theory"><span class="header-section-number">5.4</span> Theory</h2>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: LoRA adapter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: LoRA adapter
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>LoRA</strong> stands for <strong>Low-Rank Adaptation</strong>. Full fine-tuning would mean updating all 1.5 billion of the base model’s numbers. A <strong>LoRA adapter</strong> is a small, separate set of numbers — a correction that gets trained instead, while the original 1.5 billion stay frozen, untouched. LoRA does not replace the base model’s weights: at inference time the model reads its usual weights <em>and</em> this correction, added on top, together — as if the correction had been written directly into the model, without the original numbers ever having changed.</p>
<p>“Low-rank” describes <em>how</em> that correction stays small: instead of training one full table of correction numbers — one for every connection in the layer — LoRA trains two much smaller tables. Multiply those two tables together and you get a full-size correction, the same shape as the layer it’s correcting, without needing to store that full-size version separately. How narrow those two tables are is the adapter’s <strong>rank</strong> (<code>r=8</code> in Step 2 below) — small by design. Fewer numbers to store and train, at the cost of only approximating what a full-size correction could do.</p>
</div>
</div>
<div id="fig-lora-lowrank" class="pipeline-diagram quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lora-lowrank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><img src="../figures/diagrams/lora_lowrank_ch05_light.svg" class="diagram-light img-fluid figure-img" alt="Two-row diagram. Row 1: a tall Table A multiplied by a wide Table B produces a full-size correction grid. Row 2: frozen base weights plus that correction equal the effective weights used at inference." width="480"></p>
<p><img src="../figures/diagrams/lora_lowrank_ch05_dark.svg" class="diagram-dark img-fluid figure-img" width="480"></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lora-lowrank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: LoRA trains two small adapter tables. Their product creates a full-size correction, which is added to the frozen base weights. The original model is not rewritten.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: epoch and loss">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: epoch and loss
</div>
</div>
<div class="callout-body-container callout-body">
<p>One <strong>epoch</strong> is one full pass through the training data — all 16 examples, once. <strong>Loss</strong> is a single number measuring how wrong the model’s predictions were on that pass; it should generally fall as training continues, the way a golf score should generally fall as you improve. Chapter 11 covers proper evaluation metrics; loss here is just a training-time signal, not a measure of correctness by itself.</p>
<p>Why more than one pass? Each pass only nudges the adapter’s weights a small amount toward the correct answers — like tightening a connection in small, controlled turns instead of one big one, so it doesn’t overshoot. One epoch barely moves the model; this chapter runs 20 so those small nudges can actually accumulate into something. The loss numbers in Step 3 (<code>4.7173</code> on epoch 1, falling to <code>0.1201</code> by epoch 20) are the visible trace of that accumulation.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Engineering Translation: training recall vs. generalization">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Engineering Translation: training recall vs.&nbsp;generalization
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Training recall</strong> is how well the model reproduces the exact examples it trained on — an open-book test where it already saw the answer key. <strong>Generalization</strong> is how well it does on something it never saw — the real test of whether it learned anything transferable. A model can score perfectly on the first and close to zero on the second; Chapter 3 built the held-out check specifically to catch that gap.</p>
</div>
</div>
</section>
<section id="why-lora-instead-of-updating-the-whole-model" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="why-lora-instead-of-updating-the-whole-model"><span class="header-section-number">5.5</span> Why LoRA instead of updating the whole model?</h2>
<p>A full fine-tune — updating all 1.5 billion parameters — is a reasonable thing to <em>want</em>: more of the model can adapt, in principle. It’s a much harder thing to actually run: 1.5 billion trainable parameters means 1.5 billion optimizer states to keep in memory, and a saved checkpoint the same multi-gigabyte size as the base model itself, for every fine-tune you ever run. LoRA trains a small fraction of that — for this chapter’s setup, about <code>0.14%</code> of the model’s parameters — and saves a corresponding adapter file measured in megabytes, not gigabytes. You’ll see the exact numbers for both in Step 2.</p>
</section>
<section id="implementation" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="implementation"><span class="header-section-number">5.6</span> Implementation</h2>
<section id="step-1-format-a-training-example-and-mask-the-prompt-out-of-the-loss" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="step-1-format-a-training-example-and-mask-the-prompt-out-of-the-loss"><span class="header-section-number">5.6.1</span> Step 1: Format a training example and mask the prompt out of the loss</h3>
</section>
</section>
<section id="what-problem-are-we-solving" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="what-problem-are-we-solving"><span class="header-section-number">5.7</span> What problem are we solving?</h2>
<p>The model shouldn’t be trained to predict the <em>question</em> — only the <em>answer</em>. This step builds the full chat-formatted text for one example, then marks every token before the assistant’s turn as “don’t compute loss here.”</p>
</section>
<section id="inputs" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="inputs"><span class="header-section-number">5.8</span> Inputs</h2>
<ul>
<li>The tokenizer loaded in Chapter 1</li>
<li>One training example (<code>instruction</code>, <code>input</code>, <code>output</code>)</li>
</ul>
</section>
<section id="expected-output" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="expected-output"><span class="header-section-number">5.9</span> Expected Output</h2>
<p>Two tensors of matching shape: the full token sequence, and a labels tensor where the prompt portion is replaced with <code>-100</code> (PyTorch’s “ignore this position” marker for loss computation).</p>
<div id="b0aa65cb" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> build_training_ids(tokenizer, example: <span class="bu">dict</span>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, torch.Tensor]:</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    user_message <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>example[<span class="st">'instruction'</span>]<span class="sc">}</span><span class="ch">\n</span><span class="sc">{</span>example[<span class="st">'input'</span>]<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    prompt_only <span class="op">=</span> tokenizer.apply_chat_template(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        [{<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: user_message}], tokenize<span class="op">=</span><span class="va">False</span>, add_generation_prompt<span class="op">=</span><span class="va">True</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    full_text <span class="op">=</span> tokenizer.apply_chat_template(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        [</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>            {<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: user_message},</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>            {<span class="st">"role"</span>: <span class="st">"assistant"</span>, <span class="st">"content"</span>: example[<span class="st">"output"</span>]},</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        tokenize<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        add_generation_prompt<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    prompt_ids <span class="op">=</span> tokenizer(prompt_only, return_tensors<span class="op">=</span><span class="st">"pt"</span>, add_special_tokens<span class="op">=</span><span class="va">False</span>)[<span class="st">"input_ids"</span>]</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    full_ids <span class="op">=</span> tokenizer(full_text, return_tensors<span class="op">=</span><span class="st">"pt"</span>, add_special_tokens<span class="op">=</span><span class="va">False</span>)[<span class="st">"input_ids"</span>]</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    labels <span class="op">=</span> full_ids.clone()</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    labels[:, : prompt_ids.shape[<span class="dv">1</span>]] <span class="op">=</span> <span class="op">-</span><span class="dv">100</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> full_ids, labels</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>input_ids, labels <span class="op">=</span> build_training_ids(tokenizer, examples[<span class="dv">0</span>])</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Full sequence: </span><span class="sc">{</span>input_ids<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> tokens, </span><span class="sc">{</span><span class="bu">int</span>((labels[<span class="dv">0</span>] <span class="op">==</span> <span class="op">-</span><span class="dv">100</span>).<span class="bu">sum</span>())<span class="sc">}</span><span class="ss"> masked (prompt)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Running this exact code prints:</p>
<pre><code>Full sequence: 92 tokens, 71 masked (prompt)</code></pre>
</section>
<section id="what-just-happened" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="what-just-happened"><span class="header-section-number">5.10</span> What just happened?</h2>
<p>92 tokens make up the full chat-formatted example; the first 71 — everything through <code>&lt;|im_start|&gt;assistant</code> — are masked out of the loss, leaving only the 21 tokens of the actual answer for the model to be trained on. This is the same masking idea Chapter 3’s baseline used in reverse: there, the answer was hidden from the model at inference time; here, everything <em>except</em> the answer is hidden from the loss at training time.</p>
</section>
<section id="production-reality" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="production-reality"><span class="header-section-number">5.11</span> Production Reality</h2>
<p>Real fine-tuning pipelines batch many examples together with padding, not one at a time — Chapter 7 covers formatting and chunking training data at scale. This chapter keeps it to one example per step deliberately, so every line of the training loop in Step 3 stays easy to read and reason about.</p>
<section id="step-2-wrap-the-base-model-with-a-lora-adapter" class="level3" data-number="5.11.1">
<h3 data-number="5.11.1" class="anchored" data-anchor-id="step-2-wrap-the-base-model-with-a-lora-adapter"><span class="header-section-number">5.11.1</span> Step 2: Wrap the base model with a LoRA adapter</h3>
</section>
</section>
<section id="what-problem-are-we-solving-1" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="what-problem-are-we-solving-1"><span class="header-section-number">5.12</span> What problem are we solving?</h2>
<p>Turn the frozen base model into one with a small, trainable adapter attached — everything else about the model stays exactly as Chapter 1 loaded it.</p>
</section>
<section id="inputs-1" class="level2" data-number="5.13">
<h2 data-number="5.13" class="anchored" data-anchor-id="inputs-1"><span class="header-section-number">5.13</span> Inputs</h2>
<ul>
<li>The loaded <code>model</code> from Chapter 1</li>
<li>A <code>LoraConfig</code> naming which layers get an adapter</li>
</ul>
</section>
<section id="expected-output-1" class="level2" data-number="5.14">
<h2 data-number="5.14" class="anchored" data-anchor-id="expected-output-1"><span class="header-section-number">5.14</span> Expected Output</h2>
<p>A wrapped model, plus a printed count of how many parameters are actually trainable.</p>
<div id="e6514a56" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> peft <span class="im">import</span> LoraConfig, TaskType, get_peft_model</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>LORA_CONFIG <span class="op">=</span> LoraConfig(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    r<span class="op">=</span><span class="dv">8</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    lora_alpha<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    lora_dropout<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    target_modules<span class="op">=</span>[<span class="st">"q_proj"</span>, <span class="st">"k_proj"</span>, <span class="st">"v_proj"</span>, <span class="st">"o_proj"</span>],</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    task_type<span class="op">=</span>TaskType.CAUSAL_LM,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>lora_model <span class="op">=</span> get_peft_model(model, LORA_CONFIG)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>lora_model.print_trainable_parameters()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Running this exact code prints:</p>
<pre><code>trainable params: 2,179,072 || all params: 1,545,893,376 || trainable%: 0.1410</code></pre>
</section>
<section id="what-just-happened-1" class="level2" data-number="5.15">
<h2 data-number="5.15" class="anchored" data-anchor-id="what-just-happened-1"><span class="header-section-number">5.15</span> What just happened?</h2>
<p><code>target_modules</code> names the specific weight matrices inside each attention layer that get a LoRA adapter attached — <code>q_proj</code>/<code>k_proj</code>/<code>v_proj</code>/<code>o_proj</code> are the query, key, value, and output projections every attention layer has. <code>r=8</code> sets the adapter’s size (its “rank” — a small number by design). The result: <code>2,179,072</code> trainable parameters out of <code>1,545,893,376</code> total — <code>0.141%</code>. Everything else in the model is frozen and will never change during this chapter’s training.</p>
</section>
<section id="production-reality-1" class="level2" data-number="5.16">
<h2 data-number="5.16" class="anchored" data-anchor-id="production-reality-1"><span class="header-section-number">5.16</span> Production Reality</h2>
<p><code>target_modules</code> and <code>r</code> are real hyperparameters a production fine-tuning pipeline would sweep, not fix once — different layers targeted, or a larger rank, trade off adapter size against how much the model can actually learn. This chapter’s challenge exercise tries a smaller <code>target_modules</code> list and shows the real effect on results.</p>
<p>One more deliberate choice, worth naming directly: this chapter’s training loop runs entirely on CPU, the same as Chapter 1’s default. A GPU or Apple Silicon (MPS) machine can fine-tune this faster, but this book keeps every reader’s numbers reproducible against the same baseline rather than depending on whichever accelerator a given machine happens to have. If you have a GPU and want to try it, <code>model.to("cuda")</code> (or <code>"mps"</code>) before Step 2, and moving <code>input_ids</code>/<code>labels</code> in <code>build_training_ids</code> to the same device, is the change — the rest of this chapter’s logic doesn’t depend on which device it runs on.</p>
<section id="step-3-fine-tune-then-measure-recall-and-generalization" class="level3" data-number="5.16.1">
<h3 data-number="5.16.1" class="anchored" data-anchor-id="step-3-fine-tune-then-measure-recall-and-generalization"><span class="header-section-number">5.16.1</span> Step 3: Fine-tune, then measure recall <em>and</em> generalization</h3>
</section>
</section>
<section id="what-problem-are-we-solving-2" class="level2" data-number="5.17">
<h2 data-number="5.17" class="anchored" data-anchor-id="what-problem-are-we-solving-2"><span class="header-section-number">5.17</span> What problem are we solving?</h2>
<p>Actually train the adapter on Chapter 2’s 16 examples, then answer Mike’s question with numbers: did the model learn these exact examples, and separately, did anything transfer to a report it never saw?</p>
</section>
<section id="inputs-2" class="level2" data-number="5.18">
<h2 data-number="5.18" class="anchored" data-anchor-id="inputs-2"><span class="header-section-number">5.18</span> Inputs</h2>
<ul>
<li>The wrapped <code>lora_model</code> from Step 2</li>
<li>Chapter 2’s 16 training examples, and its held-out report’s 2 examples</li>
<li>Chapter 3’s <code>run_baseline</code> harness, reused unchanged</li>
</ul>
</section>
<section id="expected-output-2" class="level2" data-number="5.19">
<h2 data-number="5.19" class="anchored" data-anchor-id="expected-output-2"><span class="header-section-number">5.19</span> Expected Output</h2>
<p>A loss that falls across 20 epochs, then two before/after score comparisons.</p>
<div id="11ce9bee" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fine_tune(lora_model, tokenizer, examples: <span class="bu">list</span>[<span class="bu">dict</span>], num_epochs: <span class="bu">int</span> <span class="op">=</span> <span class="dv">20</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    lora_model.train()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.AdamW(lora_model.parameters(), lr<span class="op">=</span><span class="fl">2e-4</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(num_epochs):</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        epoch_loss <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> example <span class="kw">in</span> examples:</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>            input_ids, labels <span class="op">=</span> build_training_ids(tokenizer, example)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> lora_model(input_ids<span class="op">=</span>input_ids, labels<span class="op">=</span>labels).loss</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>            loss.backward()</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>            optimizer.step()</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>            optimizer.zero_grad()</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>            epoch_loss <span class="op">+=</span> loss.item()</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> (epoch <span class="op">+</span> <span class="dv">1</span>) <span class="op">%</span> <span class="dv">5</span> <span class="op">==</span> <span class="dv">0</span> <span class="kw">or</span> epoch <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="ss">f"  epoch </span><span class="sc">{</span>epoch <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>num_epochs<span class="sc">}</span><span class="ss">: avg loss </span><span class="sc">{</span>epoch_loss <span class="op">/</span> <span class="bu">len</span>(examples)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    lora_model.<span class="bu">eval</span>()</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score(results: <span class="bu">list</span>[<span class="bu">dict</span>]) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">int</span>, <span class="bu">int</span>]:</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>(r[<span class="st">"matched_expected"</span>] <span class="cf">for</span> r <span class="kw">in</span> results), <span class="bu">len</span>(results)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Before fine-tuning:"</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Training baseline:  </span><span class="sc">{</span>score(run_baseline(model, tokenizer, examples))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Held-out baseline:  </span><span class="sc">{</span>score(run_baseline(model, tokenizer, held_out_examples))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>fine_tune(lora_model, tokenizer, examples)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"After fine-tuning:"</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Training recall:         </span><span class="sc">{</span>score(run_baseline(lora_model, tokenizer, examples))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Held-out generalization: </span><span class="sc">{</span>score(run_baseline(lora_model, tokenizer, held_out_examples))<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Running this exact code prints:</p>
<pre><code>Before fine-tuning:
  Training baseline:  0/16
  Held-out baseline:  0/2

  epoch 1/20: avg loss 4.7173
  epoch 5/20: avg loss 1.2688
  epoch 10/20: avg loss 0.3360
  epoch 15/20: avg loss 0.1850
  epoch 20/20: avg loss 0.1201

After fine-tuning:
  Training recall:         13/16
  Held-out generalization: 0/2</code></pre>
</section>
<section id="what-just-happened-2" class="level2" data-number="5.20">
<h2 data-number="5.20" class="anchored" data-anchor-id="what-just-happened-2"><span class="header-section-number">5.20</span> What just happened?</h2>
<div id="fig-recall-gap" class="pipeline-diagram quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-recall-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><img src="../figures/diagrams/recall_gap_ch05_light.svg" class="diagram-light img-fluid figure-img" alt="Grouped bar chart. Training set questions rise from an exact-match score of 0 of 16 before fine-tuning to 13 of 16 after. Held-out report questions stay flat at 0 of 2, both before and after fine-tuning." width="440"></p>
<p><img src="../figures/diagrams/recall_gap_ch05_dark.svg" class="diagram-dark img-fluid figure-img" width="440"></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-recall-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: The same fine-tune produces two very different outcomes — training recall jumps from 0/16 to 13/16, while held-out generalization stays flat at 0/2.
</figcaption>
</figure>
</div>
<p>Be precise about what this run actually shows: fine-tuning <strong>changed</strong> the model, not simply “improved” it. Training recall jumped from <code>0/16</code> to <code>13/16</code> — real, measurable learning, not a training artifact. Held-out generalization stayed at <code>0/2</code>, exactly where it started. Sixteen examples was enough for this small model to memorize sixteen answers; it was not enough to teach it anything that transfers to a report it never saw. That’s not a bug — it’s the honest, predictable result of a training set this size, and precisely why Chapter 2 reserved that report in the first place.</p>
<p>Of the 18 total questions across both checks (16 training + 2 held-out), 13 training answers came back right, which leaves 5 wrong — 3 from the training set, 2 from the held-out report. Looking at <em>which</em> answers came back wrong is more revealing than the scores alone. Every one of those 5 is a real answer from a <em>different</em> report, borrowed wholesale — never an invented guess:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Expected</th>
<th>Model said</th>
<th>Actually belongs to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Report #3, activity planned</td>
<td><code>CONTINUE RIGGING UP...</code></td>
<td><code>CONTINUE BUILDING CURVE TO 65°</code></td>
<td>Report #36</td>
</tr>
<tr class="even">
<td>Report #36, present ops</td>
<td><code>BUILDING CURVE SECTION...</code></td>
<td><code>PIPE FREE, TRIP OUT OF HOLE...</code></td>
<td>Report #38</td>
</tr>
<tr class="odd">
<td>Report #48, present ops</td>
<td><code>LAYING DOWN COOLING BHA 31</code></td>
<td><code>CIRCULATE FOR TEMPERATURE</code></td>
<td>Report #49</td>
</tr>
<tr class="even">
<td>Report #37 (held-out), present ops</td>
<td><code>RIG UP SCHLUMBERGER...</code></td>
<td><code>PIPE FREE, TRIP OUT OF HOLE...</code></td>
<td>Report #38</td>
</tr>
<tr class="odd">
<td>Report #37 (held-out), activity planned</td>
<td><code>RUN UBI LOG...</code></td>
<td><code>CONTINUE BUILDING CURVE TO 65°</code></td>
<td>Report #36</td>
</tr>
</tbody>
</table>
<p>The fine-tuned model didn’t get vaguer or more hesitant on questions it couldn’t answer — the way the honest, ungrounded base model did back in Chapter 3. It got <em>more</em> confident, and confidently wrong, reaching for the nearest memorized answer instead. That’s a materially worse failure mode for a production system than “I don’t know,” and it’s the direct consequence of training on too little, too narrow a dataset.</p>
<p>The principle behind all three results together: a tiny fine-tune can teach a model to prefer the <em>shape</em> of your archive — its vocabulary, its formatting, the fact that answers are short, well-specific field values — without teaching it reliable judgment over reports it hasn’t seen. Shape is real and worth having. It is not the same thing as judgment, and this chapter’s numbers are exactly what the difference looks like.</p>
</section>
<section id="practical-exercise" class="level2" data-number="5.21">
<h2 data-number="5.21" class="anchored" data-anchor-id="practical-exercise"><span class="header-section-number">5.21</span> Practical exercise</h2>
<p>🟢 <strong>Beginner</strong></p>
<p><strong>Try it yourself:</strong> run <code>python code/chapter_05/first_lora_finetune.py</code> from inside <code>book/</code> (it takes about 5 minutes on CPU) and watch the loss fall across the 20 epochs.</p>
<p><strong>You’ll know it worked when:</strong> you see <code>Training recall: 13/16</code> and <code>Held-out generalization: 0/2</code> — and you can explain, in one sentence, why those two numbers moving so differently is exactly the point.</p>
</section>
<section id="field-notes" class="level2" data-number="5.22">
<h2 data-number="5.22" class="anchored" data-anchor-id="field-notes"><span class="header-section-number">5.22</span> Field notes</h2>
<div class="callout callout-style-default callout-warning callout-titled" title="Field notes: wrong, but never randomly wrong">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Field notes: wrong, but never randomly wrong
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Query:</strong> every one of this chapter’s 5 wrong answers (3 training misses, both held-out misses), collected as a set.</p>
<p><strong>Result:</strong> all 5 are word-for-word answers that belong to <em>other</em> real reports in the training set — <code>"PIPE FREE, TRIP OUT OF HOLE FOR BHA INSPECTION"</code> (really report #38’s answer) shows up twice, once for report #36’s question and once for the held-out report #37’s question.</p>
<p><strong>Why:</strong> with only 16 examples and 20 epochs of repetition, the model learned a shortcut: <em>produce something that looks like a report answer from this well</em>, without reliably learning <em>which</em> answer belongs to <em>which specific report</em>. Its confusion isn’t noise — it consistently reaches for one of a small set of memorized, real sentences.</p>
<p><strong>Lesson:</strong> a fine-tuned model’s mistakes are diagnostic. Random gibberish would suggest something broken in training; consistently borrowed real answers point specifically at “not enough distinct training signal to tell reports apart” — exactly what Chapter 6’s data quality gate and Chapter 7’s richer training examples exist to fix.</p>
</div>
</div>
</section>
<section id="challenge-exercise" class="level2" data-number="5.23">
<h2 data-number="5.23" class="anchored" data-anchor-id="challenge-exercise"><span class="header-section-number">5.23</span> Challenge exercise</h2>
<p>🟠 <strong>Intermediate</strong></p>
<p><strong>Challenge:</strong> Step 2 targets all four attention projections (<code>q_proj</code>, <code>k_proj</code>, <code>v_proj</code>, <code>o_proj</code>). A more common minimal LoRA setup only targets <code>q_proj</code> and <code>v_proj</code>. Rerun fine-tuning with that lighter config and see whether training recall changes. A reference solution is at <code>code/chapter_05/challenge/challenge.py</code> — on a real run, it trains <code>1,089,536</code> parameters (<code>0.0705%</code>, about half of this chapter’s setup) and scores <code>10/16</code> training recall, down from <code>13/16</code>.</p>
</section>
<section id="key-takeaways" class="level2" data-number="5.24">
<h2 data-number="5.24" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">5.24</span> Key takeaways</h2>
<ul>
<li>A LoRA adapter trains a small fraction of a model’s parameters (here, <code>0.141%</code>) while the rest stay frozen — a real fine-tune, not a simulation of one, at a fraction of full fine-tuning’s cost.</li>
<li>Training recall and generalization are different claims that need different evidence. This chapter’s model aced the first (<code>0/16</code> → <code>13/16</code>) and made zero progress on the second (<code>0/2</code> → <code>0/2</code>), on the exact same fine-tune.</li>
<li>A fine-tuned model’s wrong answers are worth reading, not just counting. Every miss here was a real, memorized answer from a <em>different</em> report — evidence of a specific, fixable data problem, not random model failure.</li>
<li>Sixteen examples is enough to prove fine-tuning works mechanically. It is deliberately not enough to teach real operational judgment — that’s what Part II’s larger, higher-quality training sets are for.</li>
</ul>
</section>
<section id="repository-files" class="level2" data-number="5.25">
<h2 data-number="5.25" class="anchored" data-anchor-id="repository-files"><span class="header-section-number">5.25</span> Repository files</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>code/chapter_05/first_lora_finetune.py</code></td>
<td>Fine-tunes a LoRA adapter on Chapter 2’s training examples and reports training/held-out scores</td>
</tr>
<tr class="even">
<td><code>code/chapter_05/challenge/challenge.py</code></td>
<td>Reference solution: a lighter <code>q_proj</code>/<code>v_proj</code>-only LoRA config</td>
</tr>
<tr class="odd">
<td><code>checkpoints/chapter_05_lora/</code></td>
<td>Generated adapter (not committed — regenerate by running the script)</td>
</tr>
<tr class="even">
<td><code>notebooks/chapter_05_explore.ipynb</code></td>
<td>Interactive companion notebook</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-caution callout-titled" title="CHECKPOINT — Chapter 5">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>CHECKPOINT — Chapter 5
</div>
</div>
<div class="callout-body-container callout-body">
<ul class="task-list">
<li><label><input type="checkbox" checked="">Fine-tuned a LoRA adapter on real training data with a plain PyTorch training loop</label></li>
<li><label><input type="checkbox" checked="">Measured a real improvement in training recall (<code>0/16</code> → <code>13/16</code>)</label></li>
<li><label><input type="checkbox" checked="">Ran a held-out generalization check for the first time, and found it did <em>not</em> improve (<code>0/2</code> → <code>0/2</code>)</label></li>
<li><label><input type="checkbox" checked="">Traced every wrong answer back to a specific, explainable cause rather than shrugging at “the model got it wrong”</label></li>
</ul>
</div>
</div>
<div class="built-box callout callout-style-default callout-tip callout-titled" title="✓ WHAT YOU BUILT">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>✓ WHAT YOU BUILT
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>first_lora_finetune.py</code></strong> — trains a LoRA adapter on Chapter 2’s 16 examples and saves it to <code>checkpoints/chapter_05_lora/</code> (about 8 MB, next to the base model’s ~2.9 GB of weights on disk). Reruns Chapter 3’s exact baseline harness before and after, against both the training set and the held-out report, so the comparison is honest and reproducible.</p>
</div>
</div>
</section>
<section id="what-can-you-do-now-that-you-couldnt-do-before" class="level2" data-number="5.26">
<h2 data-number="5.26" class="anchored" data-anchor-id="what-can-you-do-now-that-you-couldnt-do-before"><span class="header-section-number">5.26</span> What can you do now that you couldn’t do before?</h2>
<p>You can fine-tune a real language model on your own data and produce real, measurable evidence of what it learned — and, just as importantly, honest evidence of what it didn’t, instead of assuming a falling loss number means the job is done.</p>
</section>
<section id="suggested-next-step" class="level2" data-number="5.27">
<h2 data-number="5.27" class="anchored" data-anchor-id="suggested-next-step"><span class="header-section-number">5.27</span> Suggested next step</h2>
<p><strong>Coming up in Chapter 6:</strong> this chapter’s fine-tune worked exactly as a 16-example, single-well dataset should: real memorization, no generalization. The obvious next move is more data — but simply pointing this same pipeline at hundreds of reports, without checking them first, would just memorize more inconsistencies faster. Chapter 6 builds a data quality gate: the checks a training set needs to pass <em>before</em> it’s trusted at the scale Part II is about to introduce.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chapter_04.html" class="pagination-link" aria-label="Tokenization and Embeddings for Domain Fine-Tuning">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Tokenization and Embeddings for Domain Fine-Tuning</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chapter_06.html" class="pagination-link" aria-label="A Data Quality Gate for Training Data">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">A Data Quality Gate for Training Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Your First LoRA Fine-Tune {#sec-chapter-05}</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="html"}</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>::: {.pipeline-diagram}</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch05_light.svg)</span>{.diagram-light width="180"}</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch05_dark.svg)</span>{.diagram-dark width="180"}</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="pdf"}</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/pipeline_ch05.pdf)</span>{width="180" fig-align="center"}</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>::: {.chapter-status}</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>Progress <span class="in">`█████░░░░░░░░`</span> **5 / 13** &amp;nbsp;·&amp;nbsp; **Estimated time:** 45-60 min &amp;nbsp;·&amp;nbsp; **Difficulty:** 🟠 Intermediate</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## Learning objectives</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>By the end of this chapter, you will be able to:</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Explain what a LoRA adapter is: a small set of extra weights trained</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  on top of a frozen base model, not a rewrite of the model itself</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Fine-tune the base model on Chapter 2's 16 training examples with a</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  plain PyTorch training loop — no framework magic hidden from you</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rerun Chapter 3's training baseline against your fine-tuned model and</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  measure a real, honest improvement</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Run, for the first time in this book, a held-out generalization check</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>  against Chapter 2's reserved report — and explain, from a real run,</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>  exactly *how* the fine-tuned model fails on it</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## Operational Problem</span></span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>Mike, the completions engineer, has watched this book build up evidence</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>for four chapters — the base model doesn't know this well's vocabulary,</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>doesn't know its specific reports, and its embeddings don't already</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>understand the shorthand. He's ready for the payoff, but wary of a</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>different failure: *"If we fine-tune this on sixteen examples, are we</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>teaching it our operation — or just teaching it to repeat sixteen</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>sentences back at us?"*</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>That's exactly the right question, and this chapter answers it two</span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a>ways, not one. It fine-tunes the base model on Chapter 2's 16 training</span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a>examples, then checks *both* whether it learned those exact examples</span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>(training recall) *and* whether that learning transfers to a report it</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>never saw during training (generalization, using Chapter 2's reserved</span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a><span class="in">`Drilling_037`</span>). Chapter 3 already scored the base model <span class="in">`0/16`</span> and</span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a><span class="in">`0/2`</span> on both. This chapter reruns that exact same harness against the</span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a>fine-tuned model — same questions, same scoring, same code — so the</span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a>comparison means something.</span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example: what the model actually trains on</span></span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a>Fine-tuning doesn't feed the model <span class="in">`instruction`</span>/<span class="in">`input`</span>/<span class="in">`output`</span></span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a>dictionaries directly — it feeds it the same chat-formatted text Chapter</span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a>1's <span class="in">`generate_reply`</span> builds, except this time with the correct answer</span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a>appended as the assistant's turn:</span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="What one training example looks like, chat-formatted"}</span>
<span id="cb8-60"><a href="#cb8-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-61"><a href="#cb8-61" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;|im_start|&gt;system</span></span>
<span id="cb8-62"><a href="#cb8-62" aria-hidden="true" tabindex="-1"></a><span class="in">You are Qwen, created by Alibaba Cloud. You are a helpful assistant.&lt;|im_end|&gt;</span></span>
<span id="cb8-63"><a href="#cb8-63" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;|im_start|&gt;user</span></span>
<span id="cb8-64"><a href="#cb8-64" aria-hidden="true" tabindex="-1"></a><span class="in">What are the present operations reported on this well?</span></span>
<span id="cb8-65"><a href="#cb8-65" aria-hidden="true" tabindex="-1"></a><span class="in">Well: FORGE 16A [78]-32 | Report #3 | Date: 2020-10-22&lt;|im_end|&gt;</span></span>
<span id="cb8-66"><a href="#cb8-66" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;|im_start|&gt;assistant</span></span>
<span id="cb8-67"><a href="#cb8-67" aria-hidden="true" tabindex="-1"></a><span class="in">RIGGING UP WITH FRONTIER CREWS AND SUPERVISION AND JW JONES TRUCKING&lt;|im_end|&gt;</span></span>
<span id="cb8-68"><a href="#cb8-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-69"><a href="#cb8-69" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-70"><a href="#cb8-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-71"><a href="#cb8-71" aria-hidden="true" tabindex="-1"></a>Fine-tuning's whole job is to adjust the model so that, given the</span>
<span id="cb8-72"><a href="#cb8-72" aria-hidden="true" tabindex="-1"></a><span class="in">`system`</span> and <span class="in">`user`</span> turns above, it becomes more likely to produce that</span>
<span id="cb8-73"><a href="#cb8-73" aria-hidden="true" tabindex="-1"></a>exact <span class="in">`assistant`</span> turn — and nothing else changes about how the model</span>
<span id="cb8-74"><a href="#cb8-74" aria-hidden="true" tabindex="-1"></a>reads or generates text.</span>
<span id="cb8-75"><a href="#cb8-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-76"><a href="#cb8-76" aria-hidden="true" tabindex="-1"></a><span class="fu">## Theory</span></span>
<span id="cb8-77"><a href="#cb8-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-78"><a href="#cb8-78" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: LoRA adapter"}</span>
<span id="cb8-79"><a href="#cb8-79" aria-hidden="true" tabindex="-1"></a>**LoRA** stands for **Low-Rank Adaptation**. Full fine-tuning would mean</span>
<span id="cb8-80"><a href="#cb8-80" aria-hidden="true" tabindex="-1"></a>updating all 1.5 billion of the base model's numbers. A **LoRA adapter**</span>
<span id="cb8-81"><a href="#cb8-81" aria-hidden="true" tabindex="-1"></a>is a small, separate set of numbers — a correction that gets trained</span>
<span id="cb8-82"><a href="#cb8-82" aria-hidden="true" tabindex="-1"></a>instead, while the original 1.5 billion stay frozen, untouched. LoRA</span>
<span id="cb8-83"><a href="#cb8-83" aria-hidden="true" tabindex="-1"></a>does not replace the base model's weights: at inference time the model</span>
<span id="cb8-84"><a href="#cb8-84" aria-hidden="true" tabindex="-1"></a>reads its usual weights *and* this correction, added on top, together —</span>
<span id="cb8-85"><a href="#cb8-85" aria-hidden="true" tabindex="-1"></a>as if the correction had been written directly into the model, without</span>
<span id="cb8-86"><a href="#cb8-86" aria-hidden="true" tabindex="-1"></a>the original numbers ever having changed.</span>
<span id="cb8-87"><a href="#cb8-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-88"><a href="#cb8-88" aria-hidden="true" tabindex="-1"></a>"Low-rank" describes *how* that correction stays small: instead of</span>
<span id="cb8-89"><a href="#cb8-89" aria-hidden="true" tabindex="-1"></a>training one full table of correction numbers — one for every</span>
<span id="cb8-90"><a href="#cb8-90" aria-hidden="true" tabindex="-1"></a>connection in the layer — LoRA trains two much smaller tables. Multiply</span>
<span id="cb8-91"><a href="#cb8-91" aria-hidden="true" tabindex="-1"></a>those two tables together and you get a full-size correction, the same</span>
<span id="cb8-92"><a href="#cb8-92" aria-hidden="true" tabindex="-1"></a>shape as the layer it's correcting, without needing to store that</span>
<span id="cb8-93"><a href="#cb8-93" aria-hidden="true" tabindex="-1"></a>full-size version separately. How narrow those two tables are is the</span>
<span id="cb8-94"><a href="#cb8-94" aria-hidden="true" tabindex="-1"></a>adapter's **rank** (<span class="in">`r=8`</span> in Step 2 below) — small by design. Fewer</span>
<span id="cb8-95"><a href="#cb8-95" aria-hidden="true" tabindex="-1"></a>numbers to store and train, at the cost of only approximating what a</span>
<span id="cb8-96"><a href="#cb8-96" aria-hidden="true" tabindex="-1"></a>full-size correction could do.</span>
<span id="cb8-97"><a href="#cb8-97" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-98"><a href="#cb8-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-99"><a href="#cb8-99" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="html"}</span>
<span id="cb8-100"><a href="#cb8-100" aria-hidden="true" tabindex="-1"></a>::: {#fig-lora-lowrank .pipeline-diagram}</span>
<span id="cb8-101"><a href="#cb8-101" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/lora_lowrank_ch05_light.svg)</span>{.diagram-light width="480" fig-alt="Two-row diagram. Row 1: a tall Table A multiplied by a wide Table B produces a full-size correction grid. Row 2: frozen base weights plus that correction equal the effective weights used at inference."}</span>
<span id="cb8-102"><a href="#cb8-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-103"><a href="#cb8-103" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/lora_lowrank_ch05_dark.svg)</span>{.diagram-dark width="480"}</span>
<span id="cb8-104"><a href="#cb8-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-105"><a href="#cb8-105" aria-hidden="true" tabindex="-1"></a>LoRA trains two small adapter tables. Their product creates a full-size correction, which is added to the frozen base weights. The original model is not rewritten.</span>
<span id="cb8-106"><a href="#cb8-106" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-107"><a href="#cb8-107" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-108"><a href="#cb8-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-109"><a href="#cb8-109" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="pdf"}</span>
<span id="cb8-110"><a href="#cb8-110" aria-hidden="true" tabindex="-1"></a><span class="al">![LoRA trains two small adapter tables. Their product creates a full-size correction, which is added to the frozen base weights. The original model is not rewritten.](../figures/diagrams/lora_lowrank_ch05.pdf)</span>{width="480" fig-align="center" #fig-lora-lowrank}</span>
<span id="cb8-111"><a href="#cb8-111" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-112"><a href="#cb8-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-113"><a href="#cb8-113" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: epoch and loss"}</span>
<span id="cb8-114"><a href="#cb8-114" aria-hidden="true" tabindex="-1"></a>One **epoch** is one full pass through the training data — all 16</span>
<span id="cb8-115"><a href="#cb8-115" aria-hidden="true" tabindex="-1"></a>examples, once. **Loss** is a single number measuring how wrong the</span>
<span id="cb8-116"><a href="#cb8-116" aria-hidden="true" tabindex="-1"></a>model's predictions were on that pass; it should generally fall as</span>
<span id="cb8-117"><a href="#cb8-117" aria-hidden="true" tabindex="-1"></a>training continues, the way a golf score should generally fall as you</span>
<span id="cb8-118"><a href="#cb8-118" aria-hidden="true" tabindex="-1"></a>improve. Chapter 11 covers proper evaluation metrics; loss here is just</span>
<span id="cb8-119"><a href="#cb8-119" aria-hidden="true" tabindex="-1"></a>a training-time signal, not a measure of correctness by itself.</span>
<span id="cb8-120"><a href="#cb8-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-121"><a href="#cb8-121" aria-hidden="true" tabindex="-1"></a>Why more than one pass? Each pass only nudges the adapter's weights a</span>
<span id="cb8-122"><a href="#cb8-122" aria-hidden="true" tabindex="-1"></a>small amount toward the correct answers — like tightening a connection</span>
<span id="cb8-123"><a href="#cb8-123" aria-hidden="true" tabindex="-1"></a>in small, controlled turns instead of one big one, so it doesn't</span>
<span id="cb8-124"><a href="#cb8-124" aria-hidden="true" tabindex="-1"></a>overshoot. One epoch barely moves the model; this chapter runs 20 so</span>
<span id="cb8-125"><a href="#cb8-125" aria-hidden="true" tabindex="-1"></a>those small nudges can actually accumulate into something. The loss</span>
<span id="cb8-126"><a href="#cb8-126" aria-hidden="true" tabindex="-1"></a>numbers in Step 3 (<span class="in">`4.7173`</span> on epoch 1, falling to <span class="in">`0.1201`</span> by epoch 20)</span>
<span id="cb8-127"><a href="#cb8-127" aria-hidden="true" tabindex="-1"></a>are the visible trace of that accumulation.</span>
<span id="cb8-128"><a href="#cb8-128" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-129"><a href="#cb8-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-130"><a href="#cb8-130" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Engineering Translation: training recall vs. generalization"}</span>
<span id="cb8-131"><a href="#cb8-131" aria-hidden="true" tabindex="-1"></a>**Training recall** is how well the model reproduces the exact examples</span>
<span id="cb8-132"><a href="#cb8-132" aria-hidden="true" tabindex="-1"></a>it trained on — an open-book test where it already saw the answer key.</span>
<span id="cb8-133"><a href="#cb8-133" aria-hidden="true" tabindex="-1"></a>**Generalization** is how well it does on something it never saw — the</span>
<span id="cb8-134"><a href="#cb8-134" aria-hidden="true" tabindex="-1"></a>real test of whether it learned anything transferable. A model can</span>
<span id="cb8-135"><a href="#cb8-135" aria-hidden="true" tabindex="-1"></a>score perfectly on the first and close to zero on the second; Chapter 3</span>
<span id="cb8-136"><a href="#cb8-136" aria-hidden="true" tabindex="-1"></a>built the held-out check specifically to catch that gap.</span>
<span id="cb8-137"><a href="#cb8-137" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-138"><a href="#cb8-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-139"><a href="#cb8-139" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why LoRA instead of updating the whole model?</span></span>
<span id="cb8-140"><a href="#cb8-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-141"><a href="#cb8-141" aria-hidden="true" tabindex="-1"></a>A full fine-tune — updating all 1.5 billion parameters — is a</span>
<span id="cb8-142"><a href="#cb8-142" aria-hidden="true" tabindex="-1"></a>reasonable thing to *want*: more of the model can adapt, in principle.</span>
<span id="cb8-143"><a href="#cb8-143" aria-hidden="true" tabindex="-1"></a>It's a much harder thing to actually run: 1.5 billion trainable</span>
<span id="cb8-144"><a href="#cb8-144" aria-hidden="true" tabindex="-1"></a>parameters means 1.5 billion optimizer states to keep in memory, and a</span>
<span id="cb8-145"><a href="#cb8-145" aria-hidden="true" tabindex="-1"></a>saved checkpoint the same multi-gigabyte size as the base model itself,</span>
<span id="cb8-146"><a href="#cb8-146" aria-hidden="true" tabindex="-1"></a>for every fine-tune you ever run. LoRA trains a small fraction of that</span>
<span id="cb8-147"><a href="#cb8-147" aria-hidden="true" tabindex="-1"></a>— for this chapter's setup, about <span class="in">`0.14%`</span> of the model's parameters —</span>
<span id="cb8-148"><a href="#cb8-148" aria-hidden="true" tabindex="-1"></a>and saves a corresponding adapter file measured in megabytes, not</span>
<span id="cb8-149"><a href="#cb8-149" aria-hidden="true" tabindex="-1"></a>gigabytes. You'll see the exact numbers for both in Step 2.</span>
<span id="cb8-150"><a href="#cb8-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-151"><a href="#cb8-151" aria-hidden="true" tabindex="-1"></a><span class="fu">## Implementation</span></span>
<span id="cb8-152"><a href="#cb8-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-153"><a href="#cb8-153" aria-hidden="true" tabindex="-1"></a><span class="fu">### Step 1: Format a training example and mask the prompt out of the loss</span></span>
<span id="cb8-154"><a href="#cb8-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-155"><a href="#cb8-155" aria-hidden="true" tabindex="-1"></a><span class="fu">## What problem are we solving?</span></span>
<span id="cb8-156"><a href="#cb8-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-157"><a href="#cb8-157" aria-hidden="true" tabindex="-1"></a>The model shouldn't be trained to predict the *question* — only the</span>
<span id="cb8-158"><a href="#cb8-158" aria-hidden="true" tabindex="-1"></a>*answer*. This step builds the full chat-formatted text for one</span>
<span id="cb8-159"><a href="#cb8-159" aria-hidden="true" tabindex="-1"></a>example, then marks every token before the assistant's turn as "don't</span>
<span id="cb8-160"><a href="#cb8-160" aria-hidden="true" tabindex="-1"></a>compute loss here."</span>
<span id="cb8-161"><a href="#cb8-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-162"><a href="#cb8-162" aria-hidden="true" tabindex="-1"></a><span class="fu">## Inputs</span></span>
<span id="cb8-163"><a href="#cb8-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-164"><a href="#cb8-164" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The tokenizer loaded in Chapter 1</span>
<span id="cb8-165"><a href="#cb8-165" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>One training example (<span class="in">`instruction`</span>, <span class="in">`input`</span>, <span class="in">`output`</span>)</span>
<span id="cb8-166"><a href="#cb8-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-167"><a href="#cb8-167" aria-hidden="true" tabindex="-1"></a><span class="fu">## Expected Output</span></span>
<span id="cb8-168"><a href="#cb8-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-169"><a href="#cb8-169" aria-hidden="true" tabindex="-1"></a>Two tensors of matching shape: the full token sequence, and a labels</span>
<span id="cb8-170"><a href="#cb8-170" aria-hidden="true" tabindex="-1"></a>tensor where the prompt portion is replaced with <span class="in">`-100`</span> (PyTorch's</span>
<span id="cb8-171"><a href="#cb8-171" aria-hidden="true" tabindex="-1"></a>"ignore this position" marker for loss computation).</span>
<span id="cb8-172"><a href="#cb8-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-175"><a href="#cb8-175" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-176"><a href="#cb8-176" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb8-177"><a href="#cb8-177" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb8-178"><a href="#cb8-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-179"><a href="#cb8-179" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> build_training_ids(tokenizer, example: <span class="bu">dict</span>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, torch.Tensor]:</span>
<span id="cb8-180"><a href="#cb8-180" aria-hidden="true" tabindex="-1"></a>    user_message <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>example[<span class="st">'instruction'</span>]<span class="sc">}</span><span class="ch">\n</span><span class="sc">{</span>example[<span class="st">'input'</span>]<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb8-181"><a href="#cb8-181" aria-hidden="true" tabindex="-1"></a>    prompt_only <span class="op">=</span> tokenizer.apply_chat_template(</span>
<span id="cb8-182"><a href="#cb8-182" aria-hidden="true" tabindex="-1"></a>        [{<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: user_message}], tokenize<span class="op">=</span><span class="va">False</span>, add_generation_prompt<span class="op">=</span><span class="va">True</span></span>
<span id="cb8-183"><a href="#cb8-183" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-184"><a href="#cb8-184" aria-hidden="true" tabindex="-1"></a>    full_text <span class="op">=</span> tokenizer.apply_chat_template(</span>
<span id="cb8-185"><a href="#cb8-185" aria-hidden="true" tabindex="-1"></a>        [</span>
<span id="cb8-186"><a href="#cb8-186" aria-hidden="true" tabindex="-1"></a>            {<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: user_message},</span>
<span id="cb8-187"><a href="#cb8-187" aria-hidden="true" tabindex="-1"></a>            {<span class="st">"role"</span>: <span class="st">"assistant"</span>, <span class="st">"content"</span>: example[<span class="st">"output"</span>]},</span>
<span id="cb8-188"><a href="#cb8-188" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb8-189"><a href="#cb8-189" aria-hidden="true" tabindex="-1"></a>        tokenize<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb8-190"><a href="#cb8-190" aria-hidden="true" tabindex="-1"></a>        add_generation_prompt<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb8-191"><a href="#cb8-191" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-192"><a href="#cb8-192" aria-hidden="true" tabindex="-1"></a>    prompt_ids <span class="op">=</span> tokenizer(prompt_only, return_tensors<span class="op">=</span><span class="st">"pt"</span>, add_special_tokens<span class="op">=</span><span class="va">False</span>)[<span class="st">"input_ids"</span>]</span>
<span id="cb8-193"><a href="#cb8-193" aria-hidden="true" tabindex="-1"></a>    full_ids <span class="op">=</span> tokenizer(full_text, return_tensors<span class="op">=</span><span class="st">"pt"</span>, add_special_tokens<span class="op">=</span><span class="va">False</span>)[<span class="st">"input_ids"</span>]</span>
<span id="cb8-194"><a href="#cb8-194" aria-hidden="true" tabindex="-1"></a>    labels <span class="op">=</span> full_ids.clone()</span>
<span id="cb8-195"><a href="#cb8-195" aria-hidden="true" tabindex="-1"></a>    labels[:, : prompt_ids.shape[<span class="dv">1</span>]] <span class="op">=</span> <span class="op">-</span><span class="dv">100</span></span>
<span id="cb8-196"><a href="#cb8-196" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> full_ids, labels</span>
<span id="cb8-197"><a href="#cb8-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-198"><a href="#cb8-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-199"><a href="#cb8-199" aria-hidden="true" tabindex="-1"></a>input_ids, labels <span class="op">=</span> build_training_ids(tokenizer, examples[<span class="dv">0</span>])</span>
<span id="cb8-200"><a href="#cb8-200" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Full sequence: </span><span class="sc">{</span>input_ids<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> tokens, </span><span class="sc">{</span><span class="bu">int</span>((labels[<span class="dv">0</span>] <span class="op">==</span> <span class="op">-</span><span class="dv">100</span>).<span class="bu">sum</span>())<span class="sc">}</span><span class="ss"> masked (prompt)"</span>)</span>
<span id="cb8-201"><a href="#cb8-201" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-202"><a href="#cb8-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-203"><a href="#cb8-203" aria-hidden="true" tabindex="-1"></a>Running this exact code prints:</span>
<span id="cb8-204"><a href="#cb8-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-205"><a href="#cb8-205" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-206"><a href="#cb8-206" aria-hidden="true" tabindex="-1"></a><span class="in">Full sequence: 92 tokens, 71 masked (prompt)</span></span>
<span id="cb8-207"><a href="#cb8-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-208"><a href="#cb8-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-209"><a href="#cb8-209" aria-hidden="true" tabindex="-1"></a><span class="fu">## What just happened?</span></span>
<span id="cb8-210"><a href="#cb8-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-211"><a href="#cb8-211" aria-hidden="true" tabindex="-1"></a>92 tokens make up the full chat-formatted example; the first 71 —</span>
<span id="cb8-212"><a href="#cb8-212" aria-hidden="true" tabindex="-1"></a>everything through <span class="in">`&lt;|im_start|&gt;assistant`</span> — are masked out of the</span>
<span id="cb8-213"><a href="#cb8-213" aria-hidden="true" tabindex="-1"></a>loss, leaving only the 21 tokens of the actual answer for the model to</span>
<span id="cb8-214"><a href="#cb8-214" aria-hidden="true" tabindex="-1"></a>be trained on. This is the same masking idea Chapter 3's baseline used</span>
<span id="cb8-215"><a href="#cb8-215" aria-hidden="true" tabindex="-1"></a>in reverse: there, the answer was hidden from the model at inference</span>
<span id="cb8-216"><a href="#cb8-216" aria-hidden="true" tabindex="-1"></a>time; here, everything *except* the answer is hidden from the loss at</span>
<span id="cb8-217"><a href="#cb8-217" aria-hidden="true" tabindex="-1"></a>training time.</span>
<span id="cb8-218"><a href="#cb8-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-219"><a href="#cb8-219" aria-hidden="true" tabindex="-1"></a><span class="fu">## Production Reality</span></span>
<span id="cb8-220"><a href="#cb8-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-221"><a href="#cb8-221" aria-hidden="true" tabindex="-1"></a>Real fine-tuning pipelines batch many examples together with padding,</span>
<span id="cb8-222"><a href="#cb8-222" aria-hidden="true" tabindex="-1"></a>not one at a time — Chapter 7 covers formatting and chunking training</span>
<span id="cb8-223"><a href="#cb8-223" aria-hidden="true" tabindex="-1"></a>data at scale. This chapter keeps it to one example per step</span>
<span id="cb8-224"><a href="#cb8-224" aria-hidden="true" tabindex="-1"></a>deliberately, so every line of the training loop in Step 3 stays easy</span>
<span id="cb8-225"><a href="#cb8-225" aria-hidden="true" tabindex="-1"></a>to read and reason about.</span>
<span id="cb8-226"><a href="#cb8-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-227"><a href="#cb8-227" aria-hidden="true" tabindex="-1"></a><span class="fu">### Step 2: Wrap the base model with a LoRA adapter</span></span>
<span id="cb8-228"><a href="#cb8-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-229"><a href="#cb8-229" aria-hidden="true" tabindex="-1"></a><span class="fu">## What problem are we solving?</span></span>
<span id="cb8-230"><a href="#cb8-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-231"><a href="#cb8-231" aria-hidden="true" tabindex="-1"></a>Turn the frozen base model into one with a small, trainable adapter</span>
<span id="cb8-232"><a href="#cb8-232" aria-hidden="true" tabindex="-1"></a>attached — everything else about the model stays exactly as Chapter 1</span>
<span id="cb8-233"><a href="#cb8-233" aria-hidden="true" tabindex="-1"></a>loaded it.</span>
<span id="cb8-234"><a href="#cb8-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-235"><a href="#cb8-235" aria-hidden="true" tabindex="-1"></a><span class="fu">## Inputs</span></span>
<span id="cb8-236"><a href="#cb8-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-237"><a href="#cb8-237" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The loaded <span class="in">`model`</span> from Chapter 1</span>
<span id="cb8-238"><a href="#cb8-238" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A <span class="in">`LoraConfig`</span> naming which layers get an adapter</span>
<span id="cb8-239"><a href="#cb8-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-240"><a href="#cb8-240" aria-hidden="true" tabindex="-1"></a><span class="fu">## Expected Output</span></span>
<span id="cb8-241"><a href="#cb8-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-242"><a href="#cb8-242" aria-hidden="true" tabindex="-1"></a>A wrapped model, plus a printed count of how many parameters are</span>
<span id="cb8-243"><a href="#cb8-243" aria-hidden="true" tabindex="-1"></a>actually trainable.</span>
<span id="cb8-244"><a href="#cb8-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-247"><a href="#cb8-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-248"><a href="#cb8-248" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb8-249"><a href="#cb8-249" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> peft <span class="im">import</span> LoraConfig, TaskType, get_peft_model</span>
<span id="cb8-250"><a href="#cb8-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-251"><a href="#cb8-251" aria-hidden="true" tabindex="-1"></a>LORA_CONFIG <span class="op">=</span> LoraConfig(</span>
<span id="cb8-252"><a href="#cb8-252" aria-hidden="true" tabindex="-1"></a>    r<span class="op">=</span><span class="dv">8</span>,</span>
<span id="cb8-253"><a href="#cb8-253" aria-hidden="true" tabindex="-1"></a>    lora_alpha<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb8-254"><a href="#cb8-254" aria-hidden="true" tabindex="-1"></a>    lora_dropout<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb8-255"><a href="#cb8-255" aria-hidden="true" tabindex="-1"></a>    target_modules<span class="op">=</span>[<span class="st">"q_proj"</span>, <span class="st">"k_proj"</span>, <span class="st">"v_proj"</span>, <span class="st">"o_proj"</span>],</span>
<span id="cb8-256"><a href="#cb8-256" aria-hidden="true" tabindex="-1"></a>    task_type<span class="op">=</span>TaskType.CAUSAL_LM,</span>
<span id="cb8-257"><a href="#cb8-257" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-258"><a href="#cb8-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-259"><a href="#cb8-259" aria-hidden="true" tabindex="-1"></a>lora_model <span class="op">=</span> get_peft_model(model, LORA_CONFIG)</span>
<span id="cb8-260"><a href="#cb8-260" aria-hidden="true" tabindex="-1"></a>lora_model.print_trainable_parameters()</span>
<span id="cb8-261"><a href="#cb8-261" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-262"><a href="#cb8-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-263"><a href="#cb8-263" aria-hidden="true" tabindex="-1"></a>Running this exact code prints:</span>
<span id="cb8-264"><a href="#cb8-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-265"><a href="#cb8-265" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-266"><a href="#cb8-266" aria-hidden="true" tabindex="-1"></a><span class="in">trainable params: 2,179,072 || all params: 1,545,893,376 || trainable%: 0.1410</span></span>
<span id="cb8-267"><a href="#cb8-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-268"><a href="#cb8-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-269"><a href="#cb8-269" aria-hidden="true" tabindex="-1"></a><span class="fu">## What just happened?</span></span>
<span id="cb8-270"><a href="#cb8-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-271"><a href="#cb8-271" aria-hidden="true" tabindex="-1"></a><span class="in">`target_modules`</span> names the specific weight matrices inside each</span>
<span id="cb8-272"><a href="#cb8-272" aria-hidden="true" tabindex="-1"></a>attention layer that get a LoRA adapter attached —</span>
<span id="cb8-273"><a href="#cb8-273" aria-hidden="true" tabindex="-1"></a><span class="in">`q_proj`</span>/<span class="in">`k_proj`</span>/<span class="in">`v_proj`</span>/<span class="in">`o_proj`</span> are the query, key, value, and</span>
<span id="cb8-274"><a href="#cb8-274" aria-hidden="true" tabindex="-1"></a>output projections every attention layer has. <span class="in">`r=8`</span> sets the adapter's</span>
<span id="cb8-275"><a href="#cb8-275" aria-hidden="true" tabindex="-1"></a>size (its "rank" — a small number by design). The result: <span class="in">`2,179,072`</span></span>
<span id="cb8-276"><a href="#cb8-276" aria-hidden="true" tabindex="-1"></a>trainable parameters out of <span class="in">`1,545,893,376`</span> total — <span class="in">`0.141%`</span>. Everything</span>
<span id="cb8-277"><a href="#cb8-277" aria-hidden="true" tabindex="-1"></a>else in the model is frozen and will never change during this chapter's</span>
<span id="cb8-278"><a href="#cb8-278" aria-hidden="true" tabindex="-1"></a>training.</span>
<span id="cb8-279"><a href="#cb8-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-280"><a href="#cb8-280" aria-hidden="true" tabindex="-1"></a><span class="fu">## Production Reality</span></span>
<span id="cb8-281"><a href="#cb8-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-282"><a href="#cb8-282" aria-hidden="true" tabindex="-1"></a><span class="in">`target_modules`</span> and <span class="in">`r`</span> are real hyperparameters a production</span>
<span id="cb8-283"><a href="#cb8-283" aria-hidden="true" tabindex="-1"></a>fine-tuning pipeline would sweep, not fix once — different layers</span>
<span id="cb8-284"><a href="#cb8-284" aria-hidden="true" tabindex="-1"></a>targeted, or a larger rank, trade off adapter size against how much the</span>
<span id="cb8-285"><a href="#cb8-285" aria-hidden="true" tabindex="-1"></a>model can actually learn. This chapter's challenge exercise tries a</span>
<span id="cb8-286"><a href="#cb8-286" aria-hidden="true" tabindex="-1"></a>smaller <span class="in">`target_modules`</span> list and shows the real effect on results.</span>
<span id="cb8-287"><a href="#cb8-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-288"><a href="#cb8-288" aria-hidden="true" tabindex="-1"></a>One more deliberate choice, worth naming directly: this chapter's</span>
<span id="cb8-289"><a href="#cb8-289" aria-hidden="true" tabindex="-1"></a>training loop runs entirely on CPU, the same as Chapter 1's default. A</span>
<span id="cb8-290"><a href="#cb8-290" aria-hidden="true" tabindex="-1"></a>GPU or Apple Silicon (MPS) machine can fine-tune this faster, but this</span>
<span id="cb8-291"><a href="#cb8-291" aria-hidden="true" tabindex="-1"></a>book keeps every reader's numbers reproducible against the same</span>
<span id="cb8-292"><a href="#cb8-292" aria-hidden="true" tabindex="-1"></a>baseline rather than depending on whichever accelerator a given machine</span>
<span id="cb8-293"><a href="#cb8-293" aria-hidden="true" tabindex="-1"></a>happens to have. If you have a GPU and want to try it, <span class="in">`model.to("cuda")`</span></span>
<span id="cb8-294"><a href="#cb8-294" aria-hidden="true" tabindex="-1"></a>(or <span class="in">`"mps"`</span>) before Step 2, and moving <span class="in">`input_ids`</span>/<span class="in">`labels`</span> in</span>
<span id="cb8-295"><a href="#cb8-295" aria-hidden="true" tabindex="-1"></a><span class="in">`build_training_ids`</span> to the same device, is the change — the rest of</span>
<span id="cb8-296"><a href="#cb8-296" aria-hidden="true" tabindex="-1"></a>this chapter's logic doesn't depend on which device it runs on.</span>
<span id="cb8-297"><a href="#cb8-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-298"><a href="#cb8-298" aria-hidden="true" tabindex="-1"></a><span class="fu">### Step 3: Fine-tune, then measure recall *and* generalization</span></span>
<span id="cb8-299"><a href="#cb8-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-300"><a href="#cb8-300" aria-hidden="true" tabindex="-1"></a><span class="fu">## What problem are we solving?</span></span>
<span id="cb8-301"><a href="#cb8-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-302"><a href="#cb8-302" aria-hidden="true" tabindex="-1"></a>Actually train the adapter on Chapter 2's 16 examples, then answer</span>
<span id="cb8-303"><a href="#cb8-303" aria-hidden="true" tabindex="-1"></a>Mike's question with numbers: did the model learn these exact examples,</span>
<span id="cb8-304"><a href="#cb8-304" aria-hidden="true" tabindex="-1"></a>and separately, did anything transfer to a report it never saw?</span>
<span id="cb8-305"><a href="#cb8-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-306"><a href="#cb8-306" aria-hidden="true" tabindex="-1"></a><span class="fu">## Inputs</span></span>
<span id="cb8-307"><a href="#cb8-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-308"><a href="#cb8-308" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The wrapped <span class="in">`lora_model`</span> from Step 2</span>
<span id="cb8-309"><a href="#cb8-309" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Chapter 2's 16 training examples, and its held-out report's 2 examples</span>
<span id="cb8-310"><a href="#cb8-310" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Chapter 3's <span class="in">`run_baseline`</span> harness, reused unchanged</span>
<span id="cb8-311"><a href="#cb8-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-312"><a href="#cb8-312" aria-hidden="true" tabindex="-1"></a><span class="fu">## Expected Output</span></span>
<span id="cb8-313"><a href="#cb8-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-314"><a href="#cb8-314" aria-hidden="true" tabindex="-1"></a>A loss that falls across 20 epochs, then two before/after score</span>
<span id="cb8-315"><a href="#cb8-315" aria-hidden="true" tabindex="-1"></a>comparisons.</span>
<span id="cb8-316"><a href="#cb8-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-319"><a href="#cb8-319" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-320"><a href="#cb8-320" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb8-321"><a href="#cb8-321" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fine_tune(lora_model, tokenizer, examples: <span class="bu">list</span>[<span class="bu">dict</span>], num_epochs: <span class="bu">int</span> <span class="op">=</span> <span class="dv">20</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb8-322"><a href="#cb8-322" aria-hidden="true" tabindex="-1"></a>    lora_model.train()</span>
<span id="cb8-323"><a href="#cb8-323" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.AdamW(lora_model.parameters(), lr<span class="op">=</span><span class="fl">2e-4</span>)</span>
<span id="cb8-324"><a href="#cb8-324" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(num_epochs):</span>
<span id="cb8-325"><a href="#cb8-325" aria-hidden="true" tabindex="-1"></a>        epoch_loss <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb8-326"><a href="#cb8-326" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> example <span class="kw">in</span> examples:</span>
<span id="cb8-327"><a href="#cb8-327" aria-hidden="true" tabindex="-1"></a>            input_ids, labels <span class="op">=</span> build_training_ids(tokenizer, example)</span>
<span id="cb8-328"><a href="#cb8-328" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> lora_model(input_ids<span class="op">=</span>input_ids, labels<span class="op">=</span>labels).loss</span>
<span id="cb8-329"><a href="#cb8-329" aria-hidden="true" tabindex="-1"></a>            loss.backward()</span>
<span id="cb8-330"><a href="#cb8-330" aria-hidden="true" tabindex="-1"></a>            optimizer.step()</span>
<span id="cb8-331"><a href="#cb8-331" aria-hidden="true" tabindex="-1"></a>            optimizer.zero_grad()</span>
<span id="cb8-332"><a href="#cb8-332" aria-hidden="true" tabindex="-1"></a>            epoch_loss <span class="op">+=</span> loss.item()</span>
<span id="cb8-333"><a href="#cb8-333" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> (epoch <span class="op">+</span> <span class="dv">1</span>) <span class="op">%</span> <span class="dv">5</span> <span class="op">==</span> <span class="dv">0</span> <span class="kw">or</span> epoch <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb8-334"><a href="#cb8-334" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="ss">f"  epoch </span><span class="sc">{</span>epoch <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>num_epochs<span class="sc">}</span><span class="ss">: avg loss </span><span class="sc">{</span>epoch_loss <span class="op">/</span> <span class="bu">len</span>(examples)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-335"><a href="#cb8-335" aria-hidden="true" tabindex="-1"></a>    lora_model.<span class="bu">eval</span>()</span>
<span id="cb8-336"><a href="#cb8-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-337"><a href="#cb8-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-338"><a href="#cb8-338" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score(results: <span class="bu">list</span>[<span class="bu">dict</span>]) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">int</span>, <span class="bu">int</span>]:</span>
<span id="cb8-339"><a href="#cb8-339" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>(r[<span class="st">"matched_expected"</span>] <span class="cf">for</span> r <span class="kw">in</span> results), <span class="bu">len</span>(results)</span>
<span id="cb8-340"><a href="#cb8-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-341"><a href="#cb8-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-342"><a href="#cb8-342" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Before fine-tuning:"</span>)</span>
<span id="cb8-343"><a href="#cb8-343" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Training baseline:  </span><span class="sc">{</span>score(run_baseline(model, tokenizer, examples))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-344"><a href="#cb8-344" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Held-out baseline:  </span><span class="sc">{</span>score(run_baseline(model, tokenizer, held_out_examples))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-345"><a href="#cb8-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-346"><a href="#cb8-346" aria-hidden="true" tabindex="-1"></a>fine_tune(lora_model, tokenizer, examples)</span>
<span id="cb8-347"><a href="#cb8-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-348"><a href="#cb8-348" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"After fine-tuning:"</span>)</span>
<span id="cb8-349"><a href="#cb8-349" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Training recall:         </span><span class="sc">{</span>score(run_baseline(lora_model, tokenizer, examples))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-350"><a href="#cb8-350" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Held-out generalization: </span><span class="sc">{</span>score(run_baseline(lora_model, tokenizer, held_out_examples))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-351"><a href="#cb8-351" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-352"><a href="#cb8-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-353"><a href="#cb8-353" aria-hidden="true" tabindex="-1"></a>Running this exact code prints:</span>
<span id="cb8-354"><a href="#cb8-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-355"><a href="#cb8-355" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-356"><a href="#cb8-356" aria-hidden="true" tabindex="-1"></a><span class="in">Before fine-tuning:</span></span>
<span id="cb8-357"><a href="#cb8-357" aria-hidden="true" tabindex="-1"></a><span class="in">  Training baseline:  0/16</span></span>
<span id="cb8-358"><a href="#cb8-358" aria-hidden="true" tabindex="-1"></a><span class="in">  Held-out baseline:  0/2</span></span>
<span id="cb8-359"><a href="#cb8-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-360"><a href="#cb8-360" aria-hidden="true" tabindex="-1"></a><span class="in">  epoch 1/20: avg loss 4.7173</span></span>
<span id="cb8-361"><a href="#cb8-361" aria-hidden="true" tabindex="-1"></a><span class="in">  epoch 5/20: avg loss 1.2688</span></span>
<span id="cb8-362"><a href="#cb8-362" aria-hidden="true" tabindex="-1"></a><span class="in">  epoch 10/20: avg loss 0.3360</span></span>
<span id="cb8-363"><a href="#cb8-363" aria-hidden="true" tabindex="-1"></a><span class="in">  epoch 15/20: avg loss 0.1850</span></span>
<span id="cb8-364"><a href="#cb8-364" aria-hidden="true" tabindex="-1"></a><span class="in">  epoch 20/20: avg loss 0.1201</span></span>
<span id="cb8-365"><a href="#cb8-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-366"><a href="#cb8-366" aria-hidden="true" tabindex="-1"></a><span class="in">After fine-tuning:</span></span>
<span id="cb8-367"><a href="#cb8-367" aria-hidden="true" tabindex="-1"></a><span class="in">  Training recall:         13/16</span></span>
<span id="cb8-368"><a href="#cb8-368" aria-hidden="true" tabindex="-1"></a><span class="in">  Held-out generalization: 0/2</span></span>
<span id="cb8-369"><a href="#cb8-369" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-370"><a href="#cb8-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-371"><a href="#cb8-371" aria-hidden="true" tabindex="-1"></a><span class="fu">## What just happened?</span></span>
<span id="cb8-372"><a href="#cb8-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-373"><a href="#cb8-373" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="html"}</span>
<span id="cb8-374"><a href="#cb8-374" aria-hidden="true" tabindex="-1"></a>::: {#fig-recall-gap .pipeline-diagram}</span>
<span id="cb8-375"><a href="#cb8-375" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/recall_gap_ch05_light.svg)</span>{.diagram-light width="440" fig-alt="Grouped bar chart. Training set questions rise from an exact-match score of 0 of 16 before fine-tuning to 13 of 16 after. Held-out report questions stay flat at 0 of 2, both before and after fine-tuning."}</span>
<span id="cb8-376"><a href="#cb8-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-377"><a href="#cb8-377" aria-hidden="true" tabindex="-1"></a><span class="al">![](../figures/diagrams/recall_gap_ch05_dark.svg)</span>{.diagram-dark width="440"}</span>
<span id="cb8-378"><a href="#cb8-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-379"><a href="#cb8-379" aria-hidden="true" tabindex="-1"></a>The same fine-tune produces two very different outcomes — training recall jumps from 0/16 to 13/16, while held-out generalization stays flat at 0/2.</span>
<span id="cb8-380"><a href="#cb8-380" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-381"><a href="#cb8-381" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-382"><a href="#cb8-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-383"><a href="#cb8-383" aria-hidden="true" tabindex="-1"></a>::: {.content-visible when-format="pdf"}</span>
<span id="cb8-384"><a href="#cb8-384" aria-hidden="true" tabindex="-1"></a><span class="al">![The same fine-tune produces two very different outcomes -- training recall jumps from 0/16 to 13/16, while held-out generalization stays flat at 0/2.](../figures/diagrams/recall_gap_ch05.pdf)</span>{width="440" fig-align="center" #fig-recall-gap}</span>
<span id="cb8-385"><a href="#cb8-385" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-386"><a href="#cb8-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-387"><a href="#cb8-387" aria-hidden="true" tabindex="-1"></a>Be precise about what this run actually shows: fine-tuning **changed**</span>
<span id="cb8-388"><a href="#cb8-388" aria-hidden="true" tabindex="-1"></a>the model, not simply "improved" it. Training recall jumped from</span>
<span id="cb8-389"><a href="#cb8-389" aria-hidden="true" tabindex="-1"></a><span class="in">`0/16`</span> to <span class="in">`13/16`</span> — real, measurable learning, not a training artifact.</span>
<span id="cb8-390"><a href="#cb8-390" aria-hidden="true" tabindex="-1"></a>Held-out generalization stayed at <span class="in">`0/2`</span>, exactly where it started.</span>
<span id="cb8-391"><a href="#cb8-391" aria-hidden="true" tabindex="-1"></a>Sixteen examples was enough for this small model to memorize sixteen</span>
<span id="cb8-392"><a href="#cb8-392" aria-hidden="true" tabindex="-1"></a>answers; it was not enough to teach it anything that transfers to a</span>
<span id="cb8-393"><a href="#cb8-393" aria-hidden="true" tabindex="-1"></a>report it never saw. That's not a bug — it's the honest, predictable</span>
<span id="cb8-394"><a href="#cb8-394" aria-hidden="true" tabindex="-1"></a>result of a training set this size, and precisely why Chapter 2</span>
<span id="cb8-395"><a href="#cb8-395" aria-hidden="true" tabindex="-1"></a>reserved that report in the first place.</span>
<span id="cb8-396"><a href="#cb8-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-397"><a href="#cb8-397" aria-hidden="true" tabindex="-1"></a>Of the 18 total questions across both checks (16 training + 2</span>
<span id="cb8-398"><a href="#cb8-398" aria-hidden="true" tabindex="-1"></a>held-out), 13 training answers came back right, which leaves 5 wrong —</span>
<span id="cb8-399"><a href="#cb8-399" aria-hidden="true" tabindex="-1"></a>3 from the training set, 2 from the held-out report. Looking at</span>
<span id="cb8-400"><a href="#cb8-400" aria-hidden="true" tabindex="-1"></a>*which* answers came back wrong is more revealing than the scores</span>
<span id="cb8-401"><a href="#cb8-401" aria-hidden="true" tabindex="-1"></a>alone. Every one of those 5 is a real answer from a *different* report,</span>
<span id="cb8-402"><a href="#cb8-402" aria-hidden="true" tabindex="-1"></a>borrowed wholesale — never an invented guess:</span>
<span id="cb8-403"><a href="#cb8-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-404"><a href="#cb8-404" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Question <span class="pp">|</span> Expected <span class="pp">|</span> Model said <span class="pp">|</span> Actually belongs to <span class="pp">|</span></span>
<span id="cb8-405"><a href="#cb8-405" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb8-406"><a href="#cb8-406" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Report #3, activity planned <span class="pp">|</span> <span class="in">`CONTINUE RIGGING UP...`</span> <span class="pp">|</span> <span class="in">`CONTINUE BUILDING CURVE TO 65°`</span> <span class="pp">|</span> Report #36 <span class="pp">|</span></span>
<span id="cb8-407"><a href="#cb8-407" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Report #36, present ops <span class="pp">|</span> <span class="in">`BUILDING CURVE SECTION...`</span> <span class="pp">|</span> <span class="in">`PIPE FREE, TRIP OUT OF HOLE...`</span> <span class="pp">|</span> Report #38 <span class="pp">|</span></span>
<span id="cb8-408"><a href="#cb8-408" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Report #48, present ops <span class="pp">|</span> <span class="in">`LAYING DOWN COOLING BHA 31`</span> <span class="pp">|</span> <span class="in">`CIRCULATE FOR TEMPERATURE`</span> <span class="pp">|</span> Report #49 <span class="pp">|</span></span>
<span id="cb8-409"><a href="#cb8-409" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Report #37 (held-out), present ops <span class="pp">|</span> <span class="in">`RIG UP SCHLUMBERGER...`</span> <span class="pp">|</span> <span class="in">`PIPE FREE, TRIP OUT OF HOLE...`</span> <span class="pp">|</span> Report #38 <span class="pp">|</span></span>
<span id="cb8-410"><a href="#cb8-410" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Report #37 (held-out), activity planned <span class="pp">|</span> <span class="in">`RUN UBI LOG...`</span> <span class="pp">|</span> <span class="in">`CONTINUE BUILDING CURVE TO 65°`</span> <span class="pp">|</span> Report #36 <span class="pp">|</span></span>
<span id="cb8-411"><a href="#cb8-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-412"><a href="#cb8-412" aria-hidden="true" tabindex="-1"></a>The fine-tuned model didn't get vaguer or more hesitant on questions it</span>
<span id="cb8-413"><a href="#cb8-413" aria-hidden="true" tabindex="-1"></a>couldn't answer — the way the honest, ungrounded base model did back in</span>
<span id="cb8-414"><a href="#cb8-414" aria-hidden="true" tabindex="-1"></a>Chapter 3. It got *more* confident, and confidently wrong, reaching for</span>
<span id="cb8-415"><a href="#cb8-415" aria-hidden="true" tabindex="-1"></a>the nearest memorized answer instead. That's a materially worse failure</span>
<span id="cb8-416"><a href="#cb8-416" aria-hidden="true" tabindex="-1"></a>mode for a production system than "I don't know," and it's the direct</span>
<span id="cb8-417"><a href="#cb8-417" aria-hidden="true" tabindex="-1"></a>consequence of training on too little, too narrow a dataset.</span>
<span id="cb8-418"><a href="#cb8-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-419"><a href="#cb8-419" aria-hidden="true" tabindex="-1"></a>The principle behind all three results together: a tiny fine-tune can</span>
<span id="cb8-420"><a href="#cb8-420" aria-hidden="true" tabindex="-1"></a>teach a model to prefer the *shape* of your archive — its vocabulary,</span>
<span id="cb8-421"><a href="#cb8-421" aria-hidden="true" tabindex="-1"></a>its formatting, the fact that answers are short, well-specific field</span>
<span id="cb8-422"><a href="#cb8-422" aria-hidden="true" tabindex="-1"></a>values — without teaching it reliable judgment over reports it hasn't</span>
<span id="cb8-423"><a href="#cb8-423" aria-hidden="true" tabindex="-1"></a>seen. Shape is real and worth having. It is not the same thing as</span>
<span id="cb8-424"><a href="#cb8-424" aria-hidden="true" tabindex="-1"></a>judgment, and this chapter's numbers are exactly what the difference</span>
<span id="cb8-425"><a href="#cb8-425" aria-hidden="true" tabindex="-1"></a>looks like.</span>
<span id="cb8-426"><a href="#cb8-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-427"><a href="#cb8-427" aria-hidden="true" tabindex="-1"></a><span class="fu">## Practical exercise</span></span>
<span id="cb8-428"><a href="#cb8-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-429"><a href="#cb8-429" aria-hidden="true" tabindex="-1"></a>🟢 **Beginner**</span>
<span id="cb8-430"><a href="#cb8-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-431"><a href="#cb8-431" aria-hidden="true" tabindex="-1"></a>**Try it yourself:** run</span>
<span id="cb8-432"><a href="#cb8-432" aria-hidden="true" tabindex="-1"></a><span class="in">`python code/chapter_05/first_lora_finetune.py`</span> from inside <span class="in">`book/`</span> (it</span>
<span id="cb8-433"><a href="#cb8-433" aria-hidden="true" tabindex="-1"></a>takes about 5 minutes on CPU) and watch the loss fall across the 20</span>
<span id="cb8-434"><a href="#cb8-434" aria-hidden="true" tabindex="-1"></a>epochs.</span>
<span id="cb8-435"><a href="#cb8-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-436"><a href="#cb8-436" aria-hidden="true" tabindex="-1"></a>**You'll know it worked when:** you see <span class="in">`Training recall: 13/16`</span> and</span>
<span id="cb8-437"><a href="#cb8-437" aria-hidden="true" tabindex="-1"></a><span class="in">`Held-out generalization: 0/2`</span> — and you can explain, in one sentence,</span>
<span id="cb8-438"><a href="#cb8-438" aria-hidden="true" tabindex="-1"></a>why those two numbers moving so differently is exactly the point.</span>
<span id="cb8-439"><a href="#cb8-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-440"><a href="#cb8-440" aria-hidden="true" tabindex="-1"></a><span class="fu">## Field notes</span></span>
<span id="cb8-441"><a href="#cb8-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-442"><a href="#cb8-442" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning title="Field notes: wrong, but never randomly wrong"}</span>
<span id="cb8-443"><a href="#cb8-443" aria-hidden="true" tabindex="-1"></a>**Query:** every one of this chapter's 5 wrong answers (3 training</span>
<span id="cb8-444"><a href="#cb8-444" aria-hidden="true" tabindex="-1"></a>misses, both held-out misses), collected as a set.</span>
<span id="cb8-445"><a href="#cb8-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-446"><a href="#cb8-446" aria-hidden="true" tabindex="-1"></a>**Result:** all 5 are word-for-word answers that belong to *other* real</span>
<span id="cb8-447"><a href="#cb8-447" aria-hidden="true" tabindex="-1"></a>reports in the training set — `"PIPE FREE, TRIP OUT OF HOLE FOR BHA</span>
<span id="cb8-448"><a href="#cb8-448" aria-hidden="true" tabindex="-1"></a>INSPECTION"` (really report #38's answer) shows up twice, once for</span>
<span id="cb8-449"><a href="#cb8-449" aria-hidden="true" tabindex="-1"></a>report #36's question and once for the held-out report #37's question.</span>
<span id="cb8-450"><a href="#cb8-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-451"><a href="#cb8-451" aria-hidden="true" tabindex="-1"></a>**Why:** with only 16 examples and 20 epochs of repetition, the model</span>
<span id="cb8-452"><a href="#cb8-452" aria-hidden="true" tabindex="-1"></a>learned a shortcut: *produce something that looks like a report answer</span>
<span id="cb8-453"><a href="#cb8-453" aria-hidden="true" tabindex="-1"></a>from this well*, without reliably learning *which* answer belongs to</span>
<span id="cb8-454"><a href="#cb8-454" aria-hidden="true" tabindex="-1"></a>*which specific report*. Its confusion isn't noise — it consistently</span>
<span id="cb8-455"><a href="#cb8-455" aria-hidden="true" tabindex="-1"></a>reaches for one of a small set of memorized, real sentences.</span>
<span id="cb8-456"><a href="#cb8-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-457"><a href="#cb8-457" aria-hidden="true" tabindex="-1"></a>**Lesson:** a fine-tuned model's mistakes are diagnostic. Random</span>
<span id="cb8-458"><a href="#cb8-458" aria-hidden="true" tabindex="-1"></a>gibberish would suggest something broken in training; consistently</span>
<span id="cb8-459"><a href="#cb8-459" aria-hidden="true" tabindex="-1"></a>borrowed real answers point specifically at "not enough distinct</span>
<span id="cb8-460"><a href="#cb8-460" aria-hidden="true" tabindex="-1"></a>training signal to tell reports apart" — exactly what Chapter 6's data</span>
<span id="cb8-461"><a href="#cb8-461" aria-hidden="true" tabindex="-1"></a>quality gate and Chapter 7's richer training examples exist to fix.</span>
<span id="cb8-462"><a href="#cb8-462" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-463"><a href="#cb8-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-464"><a href="#cb8-464" aria-hidden="true" tabindex="-1"></a><span class="fu">## Challenge exercise</span></span>
<span id="cb8-465"><a href="#cb8-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-466"><a href="#cb8-466" aria-hidden="true" tabindex="-1"></a>🟠 **Intermediate**</span>
<span id="cb8-467"><a href="#cb8-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-468"><a href="#cb8-468" aria-hidden="true" tabindex="-1"></a>**Challenge:** Step 2 targets all four attention projections</span>
<span id="cb8-469"><a href="#cb8-469" aria-hidden="true" tabindex="-1"></a>(<span class="in">`q_proj`</span>, <span class="in">`k_proj`</span>, <span class="in">`v_proj`</span>, <span class="in">`o_proj`</span>). A more common minimal LoRA</span>
<span id="cb8-470"><a href="#cb8-470" aria-hidden="true" tabindex="-1"></a>setup only targets <span class="in">`q_proj`</span> and <span class="in">`v_proj`</span>. Rerun fine-tuning with that</span>
<span id="cb8-471"><a href="#cb8-471" aria-hidden="true" tabindex="-1"></a>lighter config and see whether training recall changes. A reference</span>
<span id="cb8-472"><a href="#cb8-472" aria-hidden="true" tabindex="-1"></a>solution is at <span class="in">`code/chapter_05/challenge/challenge.py`</span> — on a real</span>
<span id="cb8-473"><a href="#cb8-473" aria-hidden="true" tabindex="-1"></a>run, it trains <span class="in">`1,089,536`</span> parameters (<span class="in">`0.0705%`</span>, about half of this</span>
<span id="cb8-474"><a href="#cb8-474" aria-hidden="true" tabindex="-1"></a>chapter's setup) and scores <span class="in">`10/16`</span> training recall, down from <span class="in">`13/16`</span>.</span>
<span id="cb8-475"><a href="#cb8-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-476"><a href="#cb8-476" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key takeaways</span></span>
<span id="cb8-477"><a href="#cb8-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-478"><a href="#cb8-478" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A LoRA adapter trains a small fraction of a model's parameters (here,</span>
<span id="cb8-479"><a href="#cb8-479" aria-hidden="true" tabindex="-1"></a>  <span class="in">`0.141%`</span>) while the rest stay frozen — a real fine-tune, not a</span>
<span id="cb8-480"><a href="#cb8-480" aria-hidden="true" tabindex="-1"></a>  simulation of one, at a fraction of full fine-tuning's cost.</span>
<span id="cb8-481"><a href="#cb8-481" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Training recall and generalization are different claims that need</span>
<span id="cb8-482"><a href="#cb8-482" aria-hidden="true" tabindex="-1"></a>  different evidence. This chapter's model aced the first (<span class="in">`0/16`</span> →</span>
<span id="cb8-483"><a href="#cb8-483" aria-hidden="true" tabindex="-1"></a>  <span class="in">`13/16`</span>) and made zero progress on the second (<span class="in">`0/2`</span> → <span class="in">`0/2`</span>), on the</span>
<span id="cb8-484"><a href="#cb8-484" aria-hidden="true" tabindex="-1"></a>  exact same fine-tune.</span>
<span id="cb8-485"><a href="#cb8-485" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A fine-tuned model's wrong answers are worth reading, not just</span>
<span id="cb8-486"><a href="#cb8-486" aria-hidden="true" tabindex="-1"></a>  counting. Every miss here was a real, memorized answer from a</span>
<span id="cb8-487"><a href="#cb8-487" aria-hidden="true" tabindex="-1"></a>  *different* report — evidence of a specific, fixable data problem,</span>
<span id="cb8-488"><a href="#cb8-488" aria-hidden="true" tabindex="-1"></a>  not random model failure.</span>
<span id="cb8-489"><a href="#cb8-489" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Sixteen examples is enough to prove fine-tuning works mechanically.</span>
<span id="cb8-490"><a href="#cb8-490" aria-hidden="true" tabindex="-1"></a>  It is deliberately not enough to teach real operational judgment —</span>
<span id="cb8-491"><a href="#cb8-491" aria-hidden="true" tabindex="-1"></a>  that's what Part II's larger, higher-quality training sets are for.</span>
<span id="cb8-492"><a href="#cb8-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-493"><a href="#cb8-493" aria-hidden="true" tabindex="-1"></a><span class="fu">## Repository files</span></span>
<span id="cb8-494"><a href="#cb8-494" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-495"><a href="#cb8-495" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> File <span class="pp">|</span> Purpose <span class="pp">|</span></span>
<span id="cb8-496"><a href="#cb8-496" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb8-497"><a href="#cb8-497" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`code/chapter_05/first_lora_finetune.py`</span> <span class="pp">|</span> Fine-tunes a LoRA adapter on Chapter 2's training examples and reports training/held-out scores <span class="pp">|</span></span>
<span id="cb8-498"><a href="#cb8-498" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`code/chapter_05/challenge/challenge.py`</span> <span class="pp">|</span> Reference solution: a lighter <span class="in">`q_proj`</span>/<span class="in">`v_proj`</span>-only LoRA config <span class="pp">|</span></span>
<span id="cb8-499"><a href="#cb8-499" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`checkpoints/chapter_05_lora/`</span> <span class="pp">|</span> Generated adapter (not committed — regenerate by running the script) <span class="pp">|</span></span>
<span id="cb8-500"><a href="#cb8-500" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`notebooks/chapter_05_explore.ipynb`</span> <span class="pp">|</span> Interactive companion notebook <span class="pp">|</span></span>
<span id="cb8-501"><a href="#cb8-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-502"><a href="#cb8-502" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="CHECKPOINT — Chapter 5"}</span>
<span id="cb8-503"><a href="#cb8-503" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Fine-tuned a LoRA adapter on real training data with a plain</span>
<span id="cb8-504"><a href="#cb8-504" aria-hidden="true" tabindex="-1"></a>      PyTorch training loop</span>
<span id="cb8-505"><a href="#cb8-505" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Measured a real improvement in training recall (<span class="in">`0/16`</span> → <span class="in">`13/16`</span>)</span>
<span id="cb8-506"><a href="#cb8-506" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Ran a held-out generalization check for the first time, and</span>
<span id="cb8-507"><a href="#cb8-507" aria-hidden="true" tabindex="-1"></a>      found it did *not* improve (<span class="in">`0/2`</span> → <span class="in">`0/2`</span>)</span>
<span id="cb8-508"><a href="#cb8-508" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[x]</span> Traced every wrong answer back to a specific, explainable cause</span>
<span id="cb8-509"><a href="#cb8-509" aria-hidden="true" tabindex="-1"></a>      rather than shrugging at "the model got it wrong"</span>
<span id="cb8-510"><a href="#cb8-510" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-511"><a href="#cb8-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-512"><a href="#cb8-512" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip .built-box title="✓ WHAT YOU BUILT"}</span>
<span id="cb8-513"><a href="#cb8-513" aria-hidden="true" tabindex="-1"></a>**`first_lora_finetune.py`** — trains a LoRA adapter on Chapter 2's 16</span>
<span id="cb8-514"><a href="#cb8-514" aria-hidden="true" tabindex="-1"></a>examples and saves it to <span class="in">`checkpoints/chapter_05_lora/`</span> (about 8 MB,</span>
<span id="cb8-515"><a href="#cb8-515" aria-hidden="true" tabindex="-1"></a>next to the base model's ~2.9 GB of weights on disk). Reruns Chapter</span>
<span id="cb8-516"><a href="#cb8-516" aria-hidden="true" tabindex="-1"></a>3's exact baseline harness before and after, against both the training</span>
<span id="cb8-517"><a href="#cb8-517" aria-hidden="true" tabindex="-1"></a>set and the held-out report, so the comparison is honest and</span>
<span id="cb8-518"><a href="#cb8-518" aria-hidden="true" tabindex="-1"></a>reproducible.</span>
<span id="cb8-519"><a href="#cb8-519" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb8-520"><a href="#cb8-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-521"><a href="#cb8-521" aria-hidden="true" tabindex="-1"></a><span class="fu">## What can you do now that you couldn't do before?</span></span>
<span id="cb8-522"><a href="#cb8-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-523"><a href="#cb8-523" aria-hidden="true" tabindex="-1"></a>You can fine-tune a real language model on your own data and produce</span>
<span id="cb8-524"><a href="#cb8-524" aria-hidden="true" tabindex="-1"></a>real, measurable evidence of what it learned — and, just as</span>
<span id="cb8-525"><a href="#cb8-525" aria-hidden="true" tabindex="-1"></a>importantly, honest evidence of what it didn't, instead of assuming a</span>
<span id="cb8-526"><a href="#cb8-526" aria-hidden="true" tabindex="-1"></a>falling loss number means the job is done.</span>
<span id="cb8-527"><a href="#cb8-527" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-528"><a href="#cb8-528" aria-hidden="true" tabindex="-1"></a><span class="fu">## Suggested next step</span></span>
<span id="cb8-529"><a href="#cb8-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-530"><a href="#cb8-530" aria-hidden="true" tabindex="-1"></a>**Coming up in Chapter 6:** this chapter's fine-tune worked exactly as</span>
<span id="cb8-531"><a href="#cb8-531" aria-hidden="true" tabindex="-1"></a>a 16-example, single-well dataset should: real memorization, no</span>
<span id="cb8-532"><a href="#cb8-532" aria-hidden="true" tabindex="-1"></a>generalization. The obvious next move is more data — but simply</span>
<span id="cb8-533"><a href="#cb8-533" aria-hidden="true" tabindex="-1"></a>pointing this same pipeline at hundreds of reports, without checking</span>
<span id="cb8-534"><a href="#cb8-534" aria-hidden="true" tabindex="-1"></a>them first, would just memorize more inconsistencies faster. Chapter 6</span>
<span id="cb8-535"><a href="#cb8-535" aria-hidden="true" tabindex="-1"></a>builds a data quality gate: the checks a training set needs to pass</span>
<span id="cb8-536"><a href="#cb8-536" aria-hidden="true" tabindex="-1"></a>*before* it's trusted at the scale Part II is about to introduce.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Fine-Tuning Local LLM for Drilling &amp; Completions</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/djimrastephane/llm-ft-drilling-completions-book/edit/main/chapters/chapter_05.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/djimrastephane/llm-ft-drilling-completions-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




</body></html>